[2025-04-23T23:28:07.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T23:28:07.758+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-23T23:27:54.155878+00:00 [queued]>
[2025-04-23T23:28:07.766+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-23T23:27:54.155878+00:00 [queued]>
[2025-04-23T23:28:07.768+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-23T23:28:07.780+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-23 23:27:54.155878+00:00
[2025-04-23T23:28:07.787+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-23T23:27:54.155878+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmphjgs157q']
[2025-04-23T23:28:07.790+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4158) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T23:28:07.790+0000] {standard_task_runner.py:105} INFO - Job 311: Subtask dbt_test
[2025-04-23T23:28:07.791+0000] {standard_task_runner.py:72} INFO - Started process 4159 to run task
[2025-04-23T23:28:07.836+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-23T23:27:54.155878+00:00 [running]> on host d01273b1fd04
[2025-04-23T23:28:07.913+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T23:27:54.155878+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T23:27:54.155878+00:00'
[2025-04-23T23:28:07.915+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T23:28:07.927+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T23:28:07.929+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-23T23:28:07.937+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T23:28:09.769+0000] {subprocess.py:93} INFO - [0m23:28:09  Running with dbt=1.8.7
[2025-04-23T23:28:10.783+0000] {subprocess.py:93} INFO - [0m23:28:10  Registered adapter: snowflake=1.8.1
[2025-04-23T23:28:11.681+0000] {subprocess.py:93} INFO - [0m23:28:11  Found 6 models, 27 data tests, 3 sources, 459 macros
[2025-04-23T23:28:11.687+0000] {subprocess.py:93} INFO - [0m23:28:11
[2025-04-23T23:28:12.379+0000] {subprocess.py:93} INFO - [0m23:28:12  Concurrency: 1 threads (target='dev')
[2025-04-23T23:28:12.380+0000] {subprocess.py:93} INFO - [0m23:28:12
[2025-04-23T23:28:12.392+0000] {subprocess.py:93} INFO - [0m23:28:12  1 of 27 START test not_null_moving_averages_close_price_14d_ma ................. [RUN]
[2025-04-23T23:28:13.396+0000] {subprocess.py:93} INFO - [0m23:28:13  1 of 27 PASS not_null_moving_averages_close_price_14d_ma ....................... [[32mPASS[0m in 1.00s]
[2025-04-23T23:28:13.399+0000] {subprocess.py:93} INFO - [0m23:28:13  2 of 27 START test not_null_moving_averages_close_price_30d_ma ................. [RUN]
[2025-04-23T23:28:13.961+0000] {subprocess.py:93} INFO - [0m23:28:13  2 of 27 PASS not_null_moving_averages_close_price_30d_ma ....................... [[32mPASS[0m in 0.56s]
[2025-04-23T23:28:13.966+0000] {subprocess.py:93} INFO - [0m23:28:13  3 of 27 START test not_null_moving_averages_close_price_7d_ma .................. [RUN]
[2025-04-23T23:28:14.446+0000] {subprocess.py:93} INFO - [0m23:28:14  3 of 27 PASS not_null_moving_averages_close_price_7d_ma ........................ [[32mPASS[0m in 0.48s]
[2025-04-23T23:28:14.450+0000] {subprocess.py:93} INFO - [0m23:28:14  4 of 27 START test not_null_moving_averages_symbol ............................. [RUN]
[2025-04-23T23:28:15.180+0000] {subprocess.py:93} INFO - [0m23:28:15  4 of 27 PASS not_null_moving_averages_symbol ................................... [[32mPASS[0m in 0.73s]
[2025-04-23T23:28:15.184+0000] {subprocess.py:93} INFO - [0m23:28:15  5 of 27 START test not_null_moving_averages_trade_date ......................... [RUN]
[2025-04-23T23:28:15.778+0000] {subprocess.py:93} INFO - [0m23:28:15  5 of 27 PASS not_null_moving_averages_trade_date ............................... [[32mPASS[0m in 0.59s]
[2025-04-23T23:28:15.783+0000] {subprocess.py:93} INFO - [0m23:28:15  6 of 27 START test not_null_rsi_rsi_14d ........................................ [RUN]
[2025-04-23T23:28:16.325+0000] {subprocess.py:93} INFO - [0m23:28:16  6 of 27 PASS not_null_rsi_rsi_14d .............................................. [[32mPASS[0m in 0.54s]
[2025-04-23T23:28:16.329+0000] {subprocess.py:93} INFO - [0m23:28:16  7 of 27 START test not_null_rsi_symbol ......................................... [RUN]
[2025-04-23T23:28:16.954+0000] {subprocess.py:93} INFO - [0m23:28:16  7 of 27 PASS not_null_rsi_symbol ............................................... [[32mPASS[0m in 0.62s]
[2025-04-23T23:28:16.958+0000] {subprocess.py:93} INFO - [0m23:28:16  8 of 27 START test not_null_rsi_trade_date ..................................... [RUN]
[2025-04-23T23:28:17.431+0000] {subprocess.py:93} INFO - [0m23:28:17  8 of 27 PASS not_null_rsi_trade_date ........................................... [[32mPASS[0m in 0.47s]
[2025-04-23T23:28:17.434+0000] {subprocess.py:93} INFO - [0m23:28:17  9 of 27 START test not_null_stock_indicators_rsi_14d ........................... [RUN]
[2025-04-23T23:28:17.880+0000] {subprocess.py:93} INFO - [0m23:28:17  9 of 27 ERROR not_null_stock_indicators_rsi_14d ................................ [[31mERROR[0m in 0.44s]
[2025-04-23T23:28:17.883+0000] {subprocess.py:93} INFO - [0m23:28:17  10 of 27 START test not_null_stock_indicators_symbol ........................... [RUN]
[2025-04-23T23:28:18.389+0000] {subprocess.py:93} INFO - [0m23:28:18  10 of 27 PASS not_null_stock_indicators_symbol ................................. [[32mPASS[0m in 0.50s]
[2025-04-23T23:28:18.394+0000] {subprocess.py:93} INFO - [0m23:28:18  11 of 27 START test not_null_stock_indicators_trade_date ....................... [RUN]
[2025-04-23T23:28:19.134+0000] {subprocess.py:93} INFO - [0m23:28:19  11 of 27 PASS not_null_stock_indicators_trade_date ............................. [[32mPASS[0m in 0.74s]
[2025-04-23T23:28:19.139+0000] {subprocess.py:93} INFO - [0m23:28:19  12 of 27 START test not_null_volume_summary_symbol ............................. [RUN]
[2025-04-23T23:28:19.635+0000] {subprocess.py:93} INFO - [0m23:28:19  12 of 27 PASS not_null_volume_summary_symbol ................................... [[32mPASS[0m in 0.49s]
[2025-04-23T23:28:19.638+0000] {subprocess.py:93} INFO - [0m23:28:19  13 of 27 START test not_null_volume_summary_total_volume ....................... [RUN]
[2025-04-23T23:28:20.064+0000] {subprocess.py:93} INFO - [0m23:28:20  13 of 27 ERROR not_null_volume_summary_total_volume ............................ [[31mERROR[0m in 0.43s]
[2025-04-23T23:28:20.068+0000] {subprocess.py:93} INFO - [0m23:28:20  14 of 27 START test not_null_volume_summary_trade_date ......................... [RUN]
[2025-04-23T23:28:20.648+0000] {subprocess.py:93} INFO - [0m23:28:20  14 of 27 PASS not_null_volume_summary_trade_date ............................... [[32mPASS[0m in 0.58s]
[2025-04-23T23:28:20.652+0000] {subprocess.py:93} INFO - [0m23:28:20  15 of 27 START test positive_values_moving_averages_close_price_14d_ma ......... [RUN]
[2025-04-23T23:28:20.667+0000] {subprocess.py:93} INFO - [0m23:28:20  15 of 27 ERROR positive_values_moving_averages_close_price_14d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-23T23:28:20.671+0000] {subprocess.py:93} INFO - [0m23:28:20  16 of 27 START test positive_values_moving_averages_close_price_30d_ma ......... [RUN]
[2025-04-23T23:28:20.678+0000] {subprocess.py:93} INFO - [0m23:28:20  16 of 27 ERROR positive_values_moving_averages_close_price_30d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-23T23:28:20.682+0000] {subprocess.py:93} INFO - [0m23:28:20  17 of 27 START test positive_values_moving_averages_close_price_7d_ma .......... [RUN]
[2025-04-23T23:28:20.691+0000] {subprocess.py:93} INFO - [0m23:28:20  17 of 27 ERROR positive_values_moving_averages_close_price_7d_ma ............... [[31mERROR[0m in 0.01s]
[2025-04-23T23:28:20.694+0000] {subprocess.py:93} INFO - [0m23:28:20  18 of 27 START test positive_values_volume_summary_total_volume ................ [RUN]
[2025-04-23T23:28:20.702+0000] {subprocess.py:93} INFO - [0m23:28:20  18 of 27 ERROR positive_values_volume_summary_total_volume ..................... [[31mERROR[0m in 0.01s]
[2025-04-23T23:28:20.705+0000] {subprocess.py:93} INFO - [0m23:28:20  19 of 27 START test range_rsi_rsi_14d__100__0 .................................. [RUN]
[2025-04-23T23:28:20.714+0000] {subprocess.py:93} INFO - [0m23:28:20  19 of 27 ERROR range_rsi_rsi_14d__100__0 ....................................... [[31mERROR[0m in 0.01s]
[2025-04-23T23:28:20.717+0000] {subprocess.py:93} INFO - [0m23:28:20  20 of 27 START test range_stock_indicators_rsi_14d__100__0 ..................... [RUN]
[2025-04-23T23:28:20.725+0000] {subprocess.py:93} INFO - [0m23:28:20  20 of 27 ERROR range_stock_indicators_rsi_14d__100__0 .......................... [[31mERROR[0m in 0.01s]
[2025-04-23T23:28:20.729+0000] {subprocess.py:93} INFO - [0m23:28:20  21 of 27 START test relationships_moving_averages_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-23T23:28:21.308+0000] {subprocess.py:93} INFO - [0m23:28:21  21 of 27 PASS relationships_moving_averages_symbol__symbol__source_raw_stock_ .. [[32mPASS[0m in 0.58s]
[2025-04-23T23:28:21.312+0000] {subprocess.py:93} INFO - [0m23:28:21  22 of 27 START test relationships_rsi_symbol__symbol__source_raw_stock_ ........ [RUN]
[2025-04-23T23:28:21.988+0000] {subprocess.py:93} INFO - [0m23:28:21  22 of 27 PASS relationships_rsi_symbol__symbol__source_raw_stock_ .............. [[32mPASS[0m in 0.67s]
[2025-04-23T23:28:21.991+0000] {subprocess.py:93} INFO - [0m23:28:21  23 of 27 START test relationships_stock_indicators_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-23T23:28:22.640+0000] {subprocess.py:93} INFO - [0m23:28:22  23 of 27 PASS relationships_stock_indicators_symbol__symbol__source_raw_stock_ . [[32mPASS[0m in 0.65s]
[2025-04-23T23:28:22.644+0000] {subprocess.py:93} INFO - [0m23:28:22  24 of 27 START test unique_moving_averages_trade_date .......................... [RUN]
[2025-04-23T23:28:23.259+0000] {subprocess.py:93} INFO - [0m23:28:23  24 of 27 FAIL 180 unique_moving_averages_trade_date ............................ [[31mFAIL 180[0m in 0.61s]
[2025-04-23T23:28:23.263+0000] {subprocess.py:93} INFO - [0m23:28:23  25 of 27 START test unique_rsi_trade_date ...................................... [RUN]
[2025-04-23T23:28:23.749+0000] {subprocess.py:93} INFO - [0m23:28:23  25 of 27 FAIL 180 unique_rsi_trade_date ........................................ [[31mFAIL 180[0m in 0.48s]
[2025-04-23T23:28:23.753+0000] {subprocess.py:93} INFO - [0m23:28:23  26 of 27 START test unique_stock_indicators_trade_date ......................... [RUN]
[2025-04-23T23:28:24.500+0000] {subprocess.py:93} INFO - [0m23:28:24  26 of 27 FAIL 180 unique_stock_indicators_trade_date ........................... [[31mFAIL 180[0m in 0.74s]
[2025-04-23T23:28:24.503+0000] {subprocess.py:93} INFO - [0m23:28:24  27 of 27 START test unique_volume_summary_trade_date ........................... [RUN]
[2025-04-23T23:28:25.165+0000] {subprocess.py:93} INFO - [0m23:28:25  27 of 27 FAIL 180 unique_volume_summary_trade_date ............................. [[31mFAIL 180[0m in 0.66s]
[2025-04-23T23:28:25.172+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.173+0000] {subprocess.py:93} INFO - [0m23:28:25  Finished running 27 data tests in 0 hours 0 minutes and 13.48 seconds (13.48s).
[2025-04-23T23:28:25.319+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.320+0000] {subprocess.py:93} INFO - [0m23:28:25  [31mCompleted with 12 errors and 0 warnings:[0m
[2025-04-23T23:28:25.321+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.323+0000] {subprocess.py:93} INFO - [0m23:28:25    Database Error in test not_null_stock_indicators_rsi_14d (models/output/schema.yml)
[2025-04-23T23:28:25.323+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-23T23:28:25.324+0000] {subprocess.py:93} INFO -   invalid identifier 'RSI_14D'
[2025-04-23T23:28:25.324+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_stock_indicators_rsi_14d.sql
[2025-04-23T23:28:25.325+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.326+0000] {subprocess.py:93} INFO - [0m23:28:25    Database Error in test not_null_volume_summary_total_volume (models/output/schema.yml)
[2025-04-23T23:28:25.326+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-23T23:28:25.327+0000] {subprocess.py:93} INFO -   invalid identifier 'TOTAL_VOLUME'
[2025-04-23T23:28:25.327+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_volume_summary_total_volume.sql
[2025-04-23T23:28:25.328+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.328+0000] {subprocess.py:93} INFO - [0m23:28:25    Compilation Error in test positive_values_moving_averages_close_price_14d_ma (models/output/schema.yml)
[2025-04-23T23:28:25.329+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:28:25.329+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.329+0000] {subprocess.py:93} INFO - [0m23:28:25    Compilation Error in test positive_values_moving_averages_close_price_30d_ma (models/output/schema.yml)
[2025-04-23T23:28:25.330+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:28:25.330+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.331+0000] {subprocess.py:93} INFO - [0m23:28:25    Compilation Error in test positive_values_moving_averages_close_price_7d_ma (models/output/schema.yml)
[2025-04-23T23:28:25.331+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:28:25.331+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.331+0000] {subprocess.py:93} INFO - [0m23:28:25    Compilation Error in test positive_values_volume_summary_total_volume (models/output/schema.yml)
[2025-04-23T23:28:25.332+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:28:25.332+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.333+0000] {subprocess.py:93} INFO - [0m23:28:25    Compilation Error in test range_rsi_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-23T23:28:25.333+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:28:25.334+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.335+0000] {subprocess.py:93} INFO - [0m23:28:25    Compilation Error in test range_stock_indicators_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-23T23:28:25.336+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:28:25.337+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.338+0000] {subprocess.py:93} INFO - [0m23:28:25  [31mFailure in test unique_moving_averages_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:28:25.338+0000] {subprocess.py:93} INFO - [0m23:28:25    Got 180 results, configured to fail if != 0
[2025-04-23T23:28:25.339+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.339+0000] {subprocess.py:93} INFO - [0m23:28:25    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_moving_averages_trade_date.sql
[2025-04-23T23:28:25.340+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.340+0000] {subprocess.py:93} INFO - [0m23:28:25  [31mFailure in test unique_rsi_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:28:25.341+0000] {subprocess.py:93} INFO - [0m23:28:25    Got 180 results, configured to fail if != 0
[2025-04-23T23:28:25.341+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.342+0000] {subprocess.py:93} INFO - [0m23:28:25    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_rsi_trade_date.sql
[2025-04-23T23:28:25.343+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.344+0000] {subprocess.py:93} INFO - [0m23:28:25  [31mFailure in test unique_stock_indicators_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:28:25.345+0000] {subprocess.py:93} INFO - [0m23:28:25    Got 180 results, configured to fail if != 0
[2025-04-23T23:28:25.345+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.346+0000] {subprocess.py:93} INFO - [0m23:28:25    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_stock_indicators_trade_date.sql
[2025-04-23T23:28:25.347+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.348+0000] {subprocess.py:93} INFO - [0m23:28:25  [31mFailure in test unique_volume_summary_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:28:25.349+0000] {subprocess.py:93} INFO - [0m23:28:25    Got 180 results, configured to fail if != 0
[2025-04-23T23:28:25.350+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.351+0000] {subprocess.py:93} INFO - [0m23:28:25    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_volume_summary_trade_date.sql
[2025-04-23T23:28:25.352+0000] {subprocess.py:93} INFO - [0m23:28:25
[2025-04-23T23:28:25.354+0000] {subprocess.py:93} INFO - [0m23:28:25  Done. PASS=15 WARN=0 ERROR=12 SKIP=0 TOTAL=27
[2025-04-23T23:28:26.053+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-23T23:28:26.063+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-23T23:28:26.067+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-23T23:27:54.155878+00:00, execution_date=20250423T232754, start_date=20250423T232807, end_date=20250423T232826
[2025-04-23T23:28:26.081+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T23:28:26.083+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 311 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 4159)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-23T23:28:26.121+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T23:28:26.144+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T23:28:26.151+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
