[2025-04-24T07:25:15.702+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T07:25:15.721+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:24:55.364920+00:00 [queued]>
[2025-04-24T07:25:15.735+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:24:55.364920+00:00 [queued]>
[2025-04-24T07:25:15.737+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T07:25:15.757+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 07:24:55.364920+00:00
[2025-04-24T07:25:15.766+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T07:24:55.364920+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmplnkli0sg']
[2025-04-24T07:25:15.769+0000] {standard_task_runner.py:105} INFO - Job 356: Subtask dbt_test
[2025-04-24T07:25:15.769+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2009) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T07:25:15.771+0000] {standard_task_runner.py:72} INFO - Started process 2010 to run task
[2025-04-24T07:25:15.833+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:24:55.364920+00:00 [running]> on host e8b5346887eb
[2025-04-24T07:25:15.925+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T07:24:55.364920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T07:24:55.364920+00:00'
[2025-04-24T07:25:15.926+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T07:25:15.940+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T07:25:15.943+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T07:25:15.951+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T07:25:17.955+0000] {subprocess.py:93} INFO - [0m07:25:17  Running with dbt=1.8.7
[2025-04-24T07:25:18.975+0000] {subprocess.py:93} INFO - [0m07:25:18  Registered adapter: snowflake=1.8.1
[2025-04-24T07:25:19.757+0000] {subprocess.py:93} INFO - [0m07:25:19  Found 7 models, 11 data tests, 3 sources, 459 macros
[2025-04-24T07:25:19.761+0000] {subprocess.py:93} INFO - [0m07:25:19
[2025-04-24T07:25:20.595+0000] {subprocess.py:93} INFO - [0m07:25:20  Concurrency: 1 threads (target='dev')
[2025-04-24T07:25:20.596+0000] {subprocess.py:93} INFO - [0m07:25:20
[2025-04-24T07:25:20.608+0000] {subprocess.py:93} INFO - [0m07:25:20  1 of 11 START test dbt_expectations_expect_column_values_to_be_between_rsi_rsi_14d__100__0  [RUN]
[2025-04-24T07:25:20.634+0000] {subprocess.py:93} INFO - [0m07:25:20  1 of 11 ERROR dbt_expectations_expect_column_values_to_be_between_rsi_rsi_14d__100__0  [[31mERROR[0m in 0.02s]
[2025-04-24T07:25:20.637+0000] {subprocess.py:93} INFO - [0m07:25:20  2 of 11 START test not_null_moving_averages_stock_id ........................... [RUN]
[2025-04-24T07:25:21.516+0000] {subprocess.py:93} INFO - [0m07:25:21  2 of 11 PASS not_null_moving_averages_stock_id ................................. [[32mPASS[0m in 0.88s]
[2025-04-24T07:25:21.519+0000] {subprocess.py:93} INFO - [0m07:25:21  3 of 11 START test not_null_rsi_stock_id ....................................... [RUN]
[2025-04-24T07:25:22.274+0000] {subprocess.py:93} INFO - [0m07:25:22  3 of 11 PASS not_null_rsi_stock_id ............................................. [[32mPASS[0m in 0.75s]
[2025-04-24T07:25:22.277+0000] {subprocess.py:93} INFO - [0m07:25:22  4 of 11 START test not_null_stock_stock_id ..................................... [RUN]
[2025-04-24T07:25:23.227+0000] {subprocess.py:93} INFO - [0m07:25:23  4 of 11 PASS not_null_stock_stock_id ........................................... [[32mPASS[0m in 0.95s]
[2025-04-24T07:25:23.231+0000] {subprocess.py:93} INFO - [0m07:25:23  5 of 11 START test not_null_stock_symbol ....................................... [RUN]
[2025-04-24T07:25:23.932+0000] {subprocess.py:93} INFO - [0m07:25:23  5 of 11 PASS not_null_stock_symbol ............................................. [[32mPASS[0m in 0.70s]
[2025-04-24T07:25:23.936+0000] {subprocess.py:93} INFO - [0m07:25:23  6 of 11 START test not_null_stock_trade_date ................................... [RUN]
[2025-04-24T07:25:24.623+0000] {subprocess.py:93} INFO - [0m07:25:24  6 of 11 PASS not_null_stock_trade_date ......................................... [[32mPASS[0m in 0.68s]
[2025-04-24T07:25:24.626+0000] {subprocess.py:93} INFO - [0m07:25:24  7 of 11 START test relationships_moving_averages_stock_id__stock_id__ref_stock_  [RUN]
[2025-04-24T07:25:25.585+0000] {subprocess.py:93} INFO - [0m07:25:25  7 of 11 PASS relationships_moving_averages_stock_id__stock_id__ref_stock_ ...... [[32mPASS[0m in 0.96s]
[2025-04-24T07:25:25.589+0000] {subprocess.py:93} INFO - [0m07:25:25  8 of 11 START test relationships_rsi_stock_id__stock_id__ref_stock_ ............ [RUN]
[2025-04-24T07:25:26.445+0000] {subprocess.py:93} INFO - [0m07:25:26  8 of 11 PASS relationships_rsi_stock_id__stock_id__ref_stock_ .................. [[32mPASS[0m in 0.85s]
[2025-04-24T07:25:26.448+0000] {subprocess.py:93} INFO - [0m07:25:26  9 of 11 START test unique_moving_averages_stock_id ............................. [RUN]
[2025-04-24T07:25:27.230+0000] {subprocess.py:93} INFO - [0m07:25:27  9 of 11 PASS unique_moving_averages_stock_id ................................... [[32mPASS[0m in 0.78s]
[2025-04-24T07:25:27.234+0000] {subprocess.py:93} INFO - [0m07:25:27  10 of 11 START test unique_rsi_stock_id ........................................ [RUN]
[2025-04-24T07:25:27.942+0000] {subprocess.py:93} INFO - [0m07:25:27  10 of 11 PASS unique_rsi_stock_id .............................................. [[32mPASS[0m in 0.71s]
[2025-04-24T07:25:27.945+0000] {subprocess.py:93} INFO - [0m07:25:27  11 of 11 START test unique_stock_stock_id ...................................... [RUN]
[2025-04-24T07:25:28.633+0000] {subprocess.py:93} INFO - [0m07:25:28  11 of 11 PASS unique_stock_stock_id ............................................ [[32mPASS[0m in 0.69s]
[2025-04-24T07:25:28.640+0000] {subprocess.py:93} INFO - [0m07:25:28
[2025-04-24T07:25:28.641+0000] {subprocess.py:93} INFO - [0m07:25:28  Finished running 11 data tests in 0 hours 0 minutes and 8.88 seconds (8.88s).
[2025-04-24T07:25:28.754+0000] {subprocess.py:93} INFO - [0m07:25:28
[2025-04-24T07:25:28.755+0000] {subprocess.py:93} INFO - [0m07:25:28  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-24T07:25:28.756+0000] {subprocess.py:93} INFO - [0m07:25:28
[2025-04-24T07:25:28.757+0000] {subprocess.py:93} INFO - [0m07:25:28    Compilation Error in test dbt_expectations_expect_column_values_to_be_between_rsi_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T07:25:28.757+0000] {subprocess.py:93} INFO -   'dbt_expectations' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T07:25:28.758+0000] {subprocess.py:93} INFO - [0m07:25:28
[2025-04-24T07:25:28.759+0000] {subprocess.py:93} INFO - [0m07:25:28  Done. PASS=10 WARN=0 ERROR=1 SKIP=0 TOTAL=11
[2025-04-24T07:25:29.649+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T07:25:29.664+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T07:25:29.675+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T07:24:55.364920+00:00, execution_date=20250424T072455, start_date=20250424T072515, end_date=20250424T072529
[2025-04-24T07:25:29.693+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T07:25:29.694+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 356 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 2010)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T07:25:29.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T07:25:29.734+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T07:25:29.740+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
