[2025-04-23T23:40:42.519+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T23:40:42.537+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-23T23:40:26.544768+00:00 [queued]>
[2025-04-23T23:40:42.547+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-23T23:40:26.544768+00:00 [queued]>
[2025-04-23T23:40:42.549+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-23T23:40:42.563+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-23 23:40:26.544768+00:00
[2025-04-23T23:40:42.571+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-23T23:40:26.544768+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmp_o5drc3_']
[2025-04-23T23:40:42.575+0000] {standard_task_runner.py:105} INFO - Job 314: Subtask dbt_test
[2025-04-23T23:40:42.575+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4796) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T23:40:42.576+0000] {standard_task_runner.py:72} INFO - Started process 4797 to run task
[2025-04-23T23:40:42.624+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-23T23:40:26.544768+00:00 [running]> on host d01273b1fd04
[2025-04-23T23:40:42.706+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T23:40:26.544768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T23:40:26.544768+00:00'
[2025-04-23T23:40:42.708+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T23:40:42.720+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T23:40:42.723+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-23T23:40:42.732+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T23:40:44.518+0000] {subprocess.py:93} INFO - [0m23:40:44  Running with dbt=1.8.7
[2025-04-23T23:40:45.465+0000] {subprocess.py:93} INFO - [0m23:40:45  Registered adapter: snowflake=1.8.1
[2025-04-23T23:40:46.120+0000] {subprocess.py:93} INFO - [0m23:40:46  Found 6 models, 27 data tests, 3 sources, 459 macros
[2025-04-23T23:40:46.125+0000] {subprocess.py:93} INFO - [0m23:40:46
[2025-04-23T23:40:46.722+0000] {subprocess.py:93} INFO - [0m23:40:46  Concurrency: 1 threads (target='dev')
[2025-04-23T23:40:46.724+0000] {subprocess.py:93} INFO - [0m23:40:46
[2025-04-23T23:40:46.738+0000] {subprocess.py:93} INFO - [0m23:40:46  1 of 27 START test not_null_moving_averages_close_price_14d_ma ................. [RUN]
[2025-04-23T23:40:47.318+0000] {subprocess.py:93} INFO - [0m23:40:47  1 of 27 PASS not_null_moving_averages_close_price_14d_ma ....................... [[32mPASS[0m in 0.58s]
[2025-04-23T23:40:47.321+0000] {subprocess.py:93} INFO - [0m23:40:47  2 of 27 START test not_null_moving_averages_close_price_30d_ma ................. [RUN]
[2025-04-23T23:40:47.930+0000] {subprocess.py:93} INFO - [0m23:40:47  2 of 27 PASS not_null_moving_averages_close_price_30d_ma ....................... [[32mPASS[0m in 0.61s]
[2025-04-23T23:40:47.934+0000] {subprocess.py:93} INFO - [0m23:40:47  3 of 27 START test not_null_moving_averages_close_price_7d_ma .................. [RUN]
[2025-04-23T23:40:48.642+0000] {subprocess.py:93} INFO - [0m23:40:48  3 of 27 PASS not_null_moving_averages_close_price_7d_ma ........................ [[32mPASS[0m in 0.71s]
[2025-04-23T23:40:48.645+0000] {subprocess.py:93} INFO - [0m23:40:48  4 of 27 START test not_null_moving_averages_symbol ............................. [RUN]
[2025-04-23T23:40:49.518+0000] {subprocess.py:93} INFO - [0m23:40:49  4 of 27 PASS not_null_moving_averages_symbol ................................... [[32mPASS[0m in 0.87s]
[2025-04-23T23:40:49.522+0000] {subprocess.py:93} INFO - [0m23:40:49  5 of 27 START test not_null_moving_averages_trade_date ......................... [RUN]
[2025-04-23T23:40:50.064+0000] {subprocess.py:93} INFO - [0m23:40:50  5 of 27 PASS not_null_moving_averages_trade_date ............................... [[32mPASS[0m in 0.54s]
[2025-04-23T23:40:50.069+0000] {subprocess.py:93} INFO - [0m23:40:50  6 of 27 START test not_null_rsi_rsi_14d ........................................ [RUN]
[2025-04-23T23:40:50.685+0000] {subprocess.py:93} INFO - [0m23:40:50  6 of 27 PASS not_null_rsi_rsi_14d .............................................. [[32mPASS[0m in 0.61s]
[2025-04-23T23:40:50.690+0000] {subprocess.py:93} INFO - [0m23:40:50  7 of 27 START test not_null_rsi_symbol ......................................... [RUN]
[2025-04-23T23:40:51.264+0000] {subprocess.py:93} INFO - [0m23:40:51  7 of 27 PASS not_null_rsi_symbol ............................................... [[32mPASS[0m in 0.57s]
[2025-04-23T23:40:51.267+0000] {subprocess.py:93} INFO - [0m23:40:51  8 of 27 START test not_null_rsi_trade_date ..................................... [RUN]
[2025-04-23T23:40:51.835+0000] {subprocess.py:93} INFO - [0m23:40:51  8 of 27 PASS not_null_rsi_trade_date ........................................... [[32mPASS[0m in 0.57s]
[2025-04-23T23:40:51.838+0000] {subprocess.py:93} INFO - [0m23:40:51  9 of 27 START test not_null_stock_indicators_rsi_14d ........................... [RUN]
[2025-04-23T23:40:52.326+0000] {subprocess.py:93} INFO - [0m23:40:52  9 of 27 ERROR not_null_stock_indicators_rsi_14d ................................ [[31mERROR[0m in 0.49s]
[2025-04-23T23:40:52.329+0000] {subprocess.py:93} INFO - [0m23:40:52  10 of 27 START test not_null_stock_indicators_symbol ........................... [RUN]
[2025-04-23T23:40:52.861+0000] {subprocess.py:93} INFO - [0m23:40:52  10 of 27 PASS not_null_stock_indicators_symbol ................................. [[32mPASS[0m in 0.53s]
[2025-04-23T23:40:52.864+0000] {subprocess.py:93} INFO - [0m23:40:52  11 of 27 START test not_null_stock_indicators_trade_date ....................... [RUN]
[2025-04-23T23:40:53.487+0000] {subprocess.py:93} INFO - [0m23:40:53  11 of 27 PASS not_null_stock_indicators_trade_date ............................. [[32mPASS[0m in 0.62s]
[2025-04-23T23:40:53.491+0000] {subprocess.py:93} INFO - [0m23:40:53  12 of 27 START test not_null_volume_summary_symbol ............................. [RUN]
[2025-04-23T23:40:54.017+0000] {subprocess.py:93} INFO - [0m23:40:54  12 of 27 PASS not_null_volume_summary_symbol ................................... [[32mPASS[0m in 0.52s]
[2025-04-23T23:40:54.019+0000] {subprocess.py:93} INFO - [0m23:40:54  13 of 27 START test not_null_volume_summary_total_volume ....................... [RUN]
[2025-04-23T23:40:54.478+0000] {subprocess.py:93} INFO - [0m23:40:54  13 of 27 ERROR not_null_volume_summary_total_volume ............................ [[31mERROR[0m in 0.46s]
[2025-04-23T23:40:54.481+0000] {subprocess.py:93} INFO - [0m23:40:54  14 of 27 START test not_null_volume_summary_trade_date ......................... [RUN]
[2025-04-23T23:40:55.037+0000] {subprocess.py:93} INFO - [0m23:40:55  14 of 27 PASS not_null_volume_summary_trade_date ............................... [[32mPASS[0m in 0.55s]
[2025-04-23T23:40:55.043+0000] {subprocess.py:93} INFO - [0m23:40:55  15 of 27 START test positive_values_moving_averages_close_price_14d_ma ......... [RUN]
[2025-04-23T23:40:55.061+0000] {subprocess.py:93} INFO - [0m23:40:55  15 of 27 ERROR positive_values_moving_averages_close_price_14d_ma .............. [[31mERROR[0m in 0.02s]
[2025-04-23T23:40:55.064+0000] {subprocess.py:93} INFO - [0m23:40:55  16 of 27 START test positive_values_moving_averages_close_price_30d_ma ......... [RUN]
[2025-04-23T23:40:55.075+0000] {subprocess.py:93} INFO - [0m23:40:55  16 of 27 ERROR positive_values_moving_averages_close_price_30d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-23T23:40:55.079+0000] {subprocess.py:93} INFO - [0m23:40:55  17 of 27 START test positive_values_moving_averages_close_price_7d_ma .......... [RUN]
[2025-04-23T23:40:55.090+0000] {subprocess.py:93} INFO - [0m23:40:55  17 of 27 ERROR positive_values_moving_averages_close_price_7d_ma ............... [[31mERROR[0m in 0.01s]
[2025-04-23T23:40:55.094+0000] {subprocess.py:93} INFO - [0m23:40:55  18 of 27 START test positive_values_volume_summary_total_volume ................ [RUN]
[2025-04-23T23:40:55.105+0000] {subprocess.py:93} INFO - [0m23:40:55  18 of 27 ERROR positive_values_volume_summary_total_volume ..................... [[31mERROR[0m in 0.01s]
[2025-04-23T23:40:55.108+0000] {subprocess.py:93} INFO - [0m23:40:55  19 of 27 START test range_rsi_rsi_14d__100__0 .................................. [RUN]
[2025-04-23T23:40:55.117+0000] {subprocess.py:93} INFO - [0m23:40:55  19 of 27 ERROR range_rsi_rsi_14d__100__0 ....................................... [[31mERROR[0m in 0.01s]
[2025-04-23T23:40:55.120+0000] {subprocess.py:93} INFO - [0m23:40:55  20 of 27 START test range_stock_indicators_rsi_14d__100__0 ..................... [RUN]
[2025-04-23T23:40:55.130+0000] {subprocess.py:93} INFO - [0m23:40:55  20 of 27 ERROR range_stock_indicators_rsi_14d__100__0 .......................... [[31mERROR[0m in 0.01s]
[2025-04-23T23:40:55.134+0000] {subprocess.py:93} INFO - [0m23:40:55  21 of 27 START test relationships_moving_averages_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-23T23:40:55.672+0000] {subprocess.py:93} INFO - [0m23:40:55  21 of 27 PASS relationships_moving_averages_symbol__symbol__source_raw_stock_ .. [[32mPASS[0m in 0.54s]
[2025-04-23T23:40:55.676+0000] {subprocess.py:93} INFO - [0m23:40:55  22 of 27 START test relationships_rsi_symbol__symbol__source_raw_stock_ ........ [RUN]
[2025-04-23T23:40:56.283+0000] {subprocess.py:93} INFO - [0m23:40:56  22 of 27 PASS relationships_rsi_symbol__symbol__source_raw_stock_ .............. [[32mPASS[0m in 0.60s]
[2025-04-23T23:40:56.287+0000] {subprocess.py:93} INFO - [0m23:40:56  23 of 27 START test relationships_stock_indicators_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-23T23:40:56.885+0000] {subprocess.py:93} INFO - [0m23:40:56  23 of 27 PASS relationships_stock_indicators_symbol__symbol__source_raw_stock_ . [[32mPASS[0m in 0.60s]
[2025-04-23T23:40:56.889+0000] {subprocess.py:93} INFO - [0m23:40:56  24 of 27 START test unique_moving_averages_trade_date .......................... [RUN]
[2025-04-23T23:40:57.397+0000] {subprocess.py:93} INFO - [0m23:40:57  24 of 27 FAIL 180 unique_moving_averages_trade_date ............................ [[31mFAIL 180[0m in 0.51s]
[2025-04-23T23:40:57.400+0000] {subprocess.py:93} INFO - [0m23:40:57  25 of 27 START test unique_rsi_trade_date ...................................... [RUN]
[2025-04-23T23:40:58.002+0000] {subprocess.py:93} INFO - [0m23:40:58  25 of 27 FAIL 180 unique_rsi_trade_date ........................................ [[31mFAIL 180[0m in 0.60s]
[2025-04-23T23:40:58.006+0000] {subprocess.py:93} INFO - [0m23:40:58  26 of 27 START test unique_stock_indicators_trade_date ......................... [RUN]
[2025-04-23T23:40:58.463+0000] {subprocess.py:93} INFO - [0m23:40:58  26 of 27 FAIL 180 unique_stock_indicators_trade_date ........................... [[31mFAIL 180[0m in 0.46s]
[2025-04-23T23:40:58.466+0000] {subprocess.py:93} INFO - [0m23:40:58  27 of 27 START test unique_volume_summary_trade_date ........................... [RUN]
[2025-04-23T23:40:59.100+0000] {subprocess.py:93} INFO - [0m23:40:59  27 of 27 FAIL 180 unique_volume_summary_trade_date ............................. [[31mFAIL 180[0m in 0.63s]
[2025-04-23T23:40:59.111+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.112+0000] {subprocess.py:93} INFO - [0m23:40:59  Finished running 27 data tests in 0 hours 0 minutes and 12.98 seconds (12.98s).
[2025-04-23T23:40:59.217+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.218+0000] {subprocess.py:93} INFO - [0m23:40:59  [31mCompleted with 12 errors and 0 warnings:[0m
[2025-04-23T23:40:59.219+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.220+0000] {subprocess.py:93} INFO - [0m23:40:59    Database Error in test not_null_stock_indicators_rsi_14d (models/output/schema.yml)
[2025-04-23T23:40:59.220+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-23T23:40:59.221+0000] {subprocess.py:93} INFO -   invalid identifier 'RSI_14D'
[2025-04-23T23:40:59.222+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_stock_indicators_rsi_14d.sql
[2025-04-23T23:40:59.223+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.224+0000] {subprocess.py:93} INFO - [0m23:40:59    Database Error in test not_null_volume_summary_total_volume (models/output/schema.yml)
[2025-04-23T23:40:59.225+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-23T23:40:59.225+0000] {subprocess.py:93} INFO -   invalid identifier 'TOTAL_VOLUME'
[2025-04-23T23:40:59.226+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_volume_summary_total_volume.sql
[2025-04-23T23:40:59.227+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.227+0000] {subprocess.py:93} INFO - [0m23:40:59    Compilation Error in test positive_values_moving_averages_close_price_14d_ma (models/output/schema.yml)
[2025-04-23T23:40:59.228+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:40:59.229+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.230+0000] {subprocess.py:93} INFO - [0m23:40:59    Compilation Error in test positive_values_moving_averages_close_price_30d_ma (models/output/schema.yml)
[2025-04-23T23:40:59.231+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:40:59.232+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.232+0000] {subprocess.py:93} INFO - [0m23:40:59    Compilation Error in test positive_values_moving_averages_close_price_7d_ma (models/output/schema.yml)
[2025-04-23T23:40:59.233+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:40:59.234+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.235+0000] {subprocess.py:93} INFO - [0m23:40:59    Compilation Error in test positive_values_volume_summary_total_volume (models/output/schema.yml)
[2025-04-23T23:40:59.235+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:40:59.236+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.237+0000] {subprocess.py:93} INFO - [0m23:40:59    Compilation Error in test range_rsi_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-23T23:40:59.238+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:40:59.239+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.239+0000] {subprocess.py:93} INFO - [0m23:40:59    Compilation Error in test range_stock_indicators_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-23T23:40:59.240+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-23T23:40:59.241+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.242+0000] {subprocess.py:93} INFO - [0m23:40:59  [31mFailure in test unique_moving_averages_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:40:59.242+0000] {subprocess.py:93} INFO - [0m23:40:59    Got 180 results, configured to fail if != 0
[2025-04-23T23:40:59.243+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.244+0000] {subprocess.py:93} INFO - [0m23:40:59    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_moving_averages_trade_date.sql
[2025-04-23T23:40:59.244+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.245+0000] {subprocess.py:93} INFO - [0m23:40:59  [31mFailure in test unique_rsi_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:40:59.246+0000] {subprocess.py:93} INFO - [0m23:40:59    Got 180 results, configured to fail if != 0
[2025-04-23T23:40:59.246+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.247+0000] {subprocess.py:93} INFO - [0m23:40:59    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_rsi_trade_date.sql
[2025-04-23T23:40:59.248+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.248+0000] {subprocess.py:93} INFO - [0m23:40:59  [31mFailure in test unique_stock_indicators_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:40:59.249+0000] {subprocess.py:93} INFO - [0m23:40:59    Got 180 results, configured to fail if != 0
[2025-04-23T23:40:59.249+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.250+0000] {subprocess.py:93} INFO - [0m23:40:59    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_stock_indicators_trade_date.sql
[2025-04-23T23:40:59.251+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.251+0000] {subprocess.py:93} INFO - [0m23:40:59  [31mFailure in test unique_volume_summary_trade_date (models/output/schema.yml)[0m
[2025-04-23T23:40:59.252+0000] {subprocess.py:93} INFO - [0m23:40:59    Got 180 results, configured to fail if != 0
[2025-04-23T23:40:59.253+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.253+0000] {subprocess.py:93} INFO - [0m23:40:59    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/unique_volume_summary_trade_date.sql
[2025-04-23T23:40:59.254+0000] {subprocess.py:93} INFO - [0m23:40:59
[2025-04-23T23:40:59.255+0000] {subprocess.py:93} INFO - [0m23:40:59  Done. PASS=15 WARN=0 ERROR=12 SKIP=0 TOTAL=27
[2025-04-23T23:41:00.036+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-23T23:41:00.049+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-23T23:41:00.058+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-23T23:40:26.544768+00:00, execution_date=20250423T234026, start_date=20250423T234042, end_date=20250423T234100
[2025-04-23T23:41:00.072+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T23:41:00.073+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 314 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 4797)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-23T23:41:00.089+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T23:41:00.107+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T23:41:00.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
