[2025-04-24T07:42:12.736+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T07:42:12.755+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:41:56.593898+00:00 [queued]>
[2025-04-24T07:42:12.765+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:41:56.593898+00:00 [queued]>
[2025-04-24T07:42:12.768+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T07:42:12.782+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 07:41:56.593898+00:00
[2025-04-24T07:42:12.791+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T07:41:56.593898+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmp_1syrjss']
[2025-04-24T07:42:12.793+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2964) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T07:42:12.794+0000] {standard_task_runner.py:105} INFO - Job 363: Subtask dbt_test
[2025-04-24T07:42:12.795+0000] {standard_task_runner.py:72} INFO - Started process 2965 to run task
[2025-04-24T07:42:12.845+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:41:56.593898+00:00 [running]> on host e8b5346887eb
[2025-04-24T07:42:12.922+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T07:41:56.593898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T07:41:56.593898+00:00'
[2025-04-24T07:42:12.923+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T07:42:12.937+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T07:42:12.939+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T07:42:12.947+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T07:42:14.854+0000] {subprocess.py:93} INFO - [0m07:42:14  Running with dbt=1.8.7
[2025-04-24T07:42:15.895+0000] {subprocess.py:93} INFO - [0m07:42:15  Registered adapter: snowflake=1.8.1
[2025-04-24T07:42:16.699+0000] {subprocess.py:93} INFO - [0m07:42:16  Found 7 models, 12 data tests, 3 sources, 459 macros
[2025-04-24T07:42:16.704+0000] {subprocess.py:93} INFO - [0m07:42:16
[2025-04-24T07:42:17.557+0000] {subprocess.py:93} INFO - [0m07:42:17  Concurrency: 1 threads (target='dev')
[2025-04-24T07:42:17.558+0000] {subprocess.py:93} INFO - [0m07:42:17
[2025-04-24T07:42:17.570+0000] {subprocess.py:93} INFO - [0m07:42:17  1 of 12 START test not_null_moving_averages_stock_id ........................... [RUN]
[2025-04-24T07:42:18.621+0000] {subprocess.py:93} INFO - [0m07:42:18  1 of 12 PASS not_null_moving_averages_stock_id ................................. [[32mPASS[0m in 1.05s]
[2025-04-24T07:42:18.624+0000] {subprocess.py:93} INFO - [0m07:42:18  2 of 12 START test not_null_rsi_stock_id ....................................... [RUN]
[2025-04-24T07:42:19.542+0000] {subprocess.py:93} INFO - [0m07:42:19  2 of 12 PASS not_null_rsi_stock_id ............................................. [[32mPASS[0m in 0.92s]
[2025-04-24T07:42:19.547+0000] {subprocess.py:93} INFO - [0m07:42:19  3 of 12 START test not_null_stock_stock_id ..................................... [RUN]
[2025-04-24T07:42:20.255+0000] {subprocess.py:93} INFO - [0m07:42:20  3 of 12 PASS not_null_stock_stock_id ........................................... [[32mPASS[0m in 0.71s]
[2025-04-24T07:42:20.258+0000] {subprocess.py:93} INFO - [0m07:42:20  4 of 12 START test not_null_stock_symbol ....................................... [RUN]
[2025-04-24T07:42:20.883+0000] {subprocess.py:93} INFO - [0m07:42:20  4 of 12 PASS not_null_stock_symbol ............................................. [[32mPASS[0m in 0.62s]
[2025-04-24T07:42:20.887+0000] {subprocess.py:93} INFO - [0m07:42:20  5 of 12 START test not_null_stock_trade_date ................................... [RUN]
[2025-04-24T07:42:21.551+0000] {subprocess.py:93} INFO - [0m07:42:21  5 of 12 PASS not_null_stock_trade_date ......................................... [[32mPASS[0m in 0.66s]
[2025-04-24T07:42:21.557+0000] {subprocess.py:93} INFO - [0m07:42:21  6 of 12 START test relationships_moving_averages_stock_id__stock_id__ref_stock_  [RUN]
[2025-04-24T07:42:22.531+0000] {subprocess.py:93} INFO - [0m07:42:22  6 of 12 PASS relationships_moving_averages_stock_id__stock_id__ref_stock_ ...... [[32mPASS[0m in 0.97s]
[2025-04-24T07:42:22.537+0000] {subprocess.py:93} INFO - [0m07:42:22  7 of 12 START test relationships_rsi_stock_id__stock_id__ref_stock_ ............ [RUN]
[2025-04-24T07:42:23.547+0000] {subprocess.py:93} INFO - [0m07:42:23  7 of 12 PASS relationships_rsi_stock_id__stock_id__ref_stock_ .................. [[32mPASS[0m in 1.01s]
[2025-04-24T07:42:23.551+0000] {subprocess.py:93} INFO - [0m07:42:23  8 of 12 START test rsi_test .................................................... [RUN]
[2025-04-24T07:42:24.297+0000] {subprocess.py:93} INFO - [0m07:42:24  8 of 12 PASS rsi_test .......................................................... [[32mPASS[0m in 0.74s]
[2025-04-24T07:42:24.302+0000] {subprocess.py:93} INFO - [0m07:42:24  9 of 12 START test rsi_test .................................................... [RUN]
[2025-04-24T07:42:24.315+0000] {subprocess.py:93} INFO - [0m07:42:24  9 of 12 ERROR rsi_test ......................................................... [[31mERROR[0m in 0.01s]
[2025-04-24T07:42:24.318+0000] {subprocess.py:93} INFO - [0m07:42:24  10 of 12 START test unique_moving_averages_stock_id ............................ [RUN]
[2025-04-24T07:42:25.012+0000] {subprocess.py:93} INFO - [0m07:42:25  10 of 12 PASS unique_moving_averages_stock_id .................................. [[32mPASS[0m in 0.69s]
[2025-04-24T07:42:25.017+0000] {subprocess.py:93} INFO - [0m07:42:25  11 of 12 START test unique_rsi_stock_id ........................................ [RUN]
[2025-04-24T07:42:25.734+0000] {subprocess.py:93} INFO - [0m07:42:25  11 of 12 PASS unique_rsi_stock_id .............................................. [[32mPASS[0m in 0.72s]
[2025-04-24T07:42:25.737+0000] {subprocess.py:93} INFO - [0m07:42:25  12 of 12 START test unique_stock_stock_id ...................................... [RUN]
[2025-04-24T07:42:26.490+0000] {subprocess.py:93} INFO - [0m07:42:26  12 of 12 PASS unique_stock_stock_id ............................................ [[32mPASS[0m in 0.75s]
[2025-04-24T07:42:26.495+0000] {subprocess.py:93} INFO - [0m07:42:26
[2025-04-24T07:42:26.496+0000] {subprocess.py:93} INFO - [0m07:42:26  Finished running 12 data tests in 0 hours 0 minutes and 9.79 seconds (9.79s).
[2025-04-24T07:42:26.629+0000] {subprocess.py:93} INFO - [0m07:42:26
[2025-04-24T07:42:26.630+0000] {subprocess.py:93} INFO - [0m07:42:26  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-24T07:42:26.631+0000] {subprocess.py:93} INFO - [0m07:42:26
[2025-04-24T07:42:26.631+0000] {subprocess.py:93} INFO - [0m07:42:26    Compilation Error in test rsi_test (models/output/schema.yml)
[2025-04-24T07:42:26.632+0000] {subprocess.py:93} INFO -   'test_custom' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T07:42:26.633+0000] {subprocess.py:93} INFO - [0m07:42:26
[2025-04-24T07:42:26.633+0000] {subprocess.py:93} INFO - [0m07:42:26  Done. PASS=11 WARN=0 ERROR=1 SKIP=0 TOTAL=12
[2025-04-24T07:42:27.531+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T07:42:27.542+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T07:42:27.547+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T07:41:56.593898+00:00, execution_date=20250424T074156, start_date=20250424T074212, end_date=20250424T074227
[2025-04-24T07:42:27.564+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T07:42:27.565+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 363 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 2965)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T07:42:27.576+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T07:42:27.597+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T07:42:27.602+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
