[2025-04-24T00:12:18.986+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:12:19.002+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:12:04.746733+00:00 [queued]>
[2025-04-24T00:12:19.011+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:12:04.746733+00:00 [queued]>
[2025-04-24T00:12:19.013+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T00:12:19.027+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 00:12:04.746733+00:00
[2025-04-24T00:12:19.036+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6428) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T00:12:19.034+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T00:12:04.746733+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmpdt4r2tgx']
[2025-04-24T00:12:19.037+0000] {standard_task_runner.py:72} INFO - Started process 6429 to run task
[2025-04-24T00:12:19.039+0000] {standard_task_runner.py:105} INFO - Job 327: Subtask dbt_test
[2025-04-24T00:12:19.086+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:12:04.746733+00:00 [running]> on host d01273b1fd04
[2025-04-24T00:12:19.163+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T00:12:04.746733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T00:12:04.746733+00:00'
[2025-04-24T00:12:19.164+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:12:19.178+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T00:12:19.180+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T00:12:19.189+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T00:12:20.984+0000] {subprocess.py:93} INFO - [0m00:12:20  Running with dbt=1.8.7
[2025-04-24T00:12:21.873+0000] {subprocess.py:93} INFO - [0m00:12:21  Registered adapter: snowflake=1.8.1
[2025-04-24T00:12:22.602+0000] {subprocess.py:93} INFO - [0m00:12:22  Found 6 models, 18 data tests, 3 sources, 459 macros
[2025-04-24T00:12:22.606+0000] {subprocess.py:93} INFO - [0m00:12:22
[2025-04-24T00:12:23.225+0000] {subprocess.py:93} INFO - [0m00:12:23  Concurrency: 1 threads (target='dev')
[2025-04-24T00:12:23.226+0000] {subprocess.py:93} INFO - [0m00:12:23
[2025-04-24T00:12:23.237+0000] {subprocess.py:93} INFO - [0m00:12:23  1 of 18 START test dbt_utils_unique_combination_of_columns_moving_averages_symbol__trade_date  [RUN]
[2025-04-24T00:12:23.256+0000] {subprocess.py:93} INFO - [0m00:12:23  1 of 18 ERROR dbt_utils_unique_combination_of_columns_moving_averages_symbol__trade_date  [[31mERROR[0m in 0.02s]
[2025-04-24T00:12:23.259+0000] {subprocess.py:93} INFO - [0m00:12:23  2 of 18 START test dbt_utils_unique_combination_of_columns_rsi_symbol__trade_date  [RUN]
[2025-04-24T00:12:23.267+0000] {subprocess.py:93} INFO - [0m00:12:23  2 of 18 ERROR dbt_utils_unique_combination_of_columns_rsi_symbol__trade_date ... [[31mERROR[0m in 0.01s]
[2025-04-24T00:12:23.270+0000] {subprocess.py:93} INFO - [0m00:12:23  3 of 18 START test dbt_utils_unique_combination_of_columns_stock_indicators_symbol__trade_date  [RUN]
[2025-04-24T00:12:23.278+0000] {subprocess.py:93} INFO - [0m00:12:23  3 of 18 ERROR dbt_utils_unique_combination_of_columns_stock_indicators_symbol__trade_date  [[31mERROR[0m in 0.01s]
[2025-04-24T00:12:23.281+0000] {subprocess.py:93} INFO - [0m00:12:23  4 of 18 START test dbt_utils_unique_combination_of_columns_volume_summary_symbol__trade_date  [RUN]
[2025-04-24T00:12:23.290+0000] {subprocess.py:93} INFO - [0m00:12:23  4 of 18 ERROR dbt_utils_unique_combination_of_columns_volume_summary_symbol__trade_date  [[31mERROR[0m in 0.01s]
[2025-04-24T00:12:23.293+0000] {subprocess.py:93} INFO - [0m00:12:23  5 of 18 START test not_null_moving_averages_close_price_14d_ma ................. [RUN]
[2025-04-24T00:12:24.018+0000] {subprocess.py:93} INFO - [0m00:12:24  5 of 18 PASS not_null_moving_averages_close_price_14d_ma ....................... [[32mPASS[0m in 0.72s]
[2025-04-24T00:12:24.021+0000] {subprocess.py:93} INFO - [0m00:12:24  6 of 18 START test not_null_moving_averages_close_price_30d_ma ................. [RUN]
[2025-04-24T00:12:24.675+0000] {subprocess.py:93} INFO - [0m00:12:24  6 of 18 PASS not_null_moving_averages_close_price_30d_ma ....................... [[32mPASS[0m in 0.65s]
[2025-04-24T00:12:24.679+0000] {subprocess.py:93} INFO - [0m00:12:24  7 of 18 START test not_null_moving_averages_close_price_7d_ma .................. [RUN]
[2025-04-24T00:12:25.552+0000] {subprocess.py:93} INFO - [0m00:12:25  7 of 18 PASS not_null_moving_averages_close_price_7d_ma ........................ [[32mPASS[0m in 0.87s]
[2025-04-24T00:12:25.555+0000] {subprocess.py:93} INFO - [0m00:12:25  8 of 18 START test not_null_moving_averages_symbol ............................. [RUN]
[2025-04-24T00:12:26.034+0000] {subprocess.py:93} INFO - [0m00:12:26  8 of 18 PASS not_null_moving_averages_symbol ................................... [[32mPASS[0m in 0.48s]
[2025-04-24T00:12:26.040+0000] {subprocess.py:93} INFO - [0m00:12:26  9 of 18 START test not_null_moving_averages_trade_date ......................... [RUN]
[2025-04-24T00:12:26.825+0000] {subprocess.py:93} INFO - [0m00:12:26  9 of 18 PASS not_null_moving_averages_trade_date ............................... [[32mPASS[0m in 0.78s]
[2025-04-24T00:12:26.829+0000] {subprocess.py:93} INFO - [0m00:12:26  10 of 18 START test not_null_rsi_rsi_14d ....................................... [RUN]
[2025-04-24T00:12:27.385+0000] {subprocess.py:93} INFO - [0m00:12:27  10 of 18 FAIL 3 not_null_rsi_rsi_14d ........................................... [[31mFAIL 3[0m in 0.55s]
[2025-04-24T00:12:27.389+0000] {subprocess.py:93} INFO - [0m00:12:27  11 of 18 START test not_null_rsi_symbol ........................................ [RUN]
[2025-04-24T00:12:27.993+0000] {subprocess.py:93} INFO - [0m00:12:27  11 of 18 PASS not_null_rsi_symbol .............................................. [[32mPASS[0m in 0.60s]
[2025-04-24T00:12:27.997+0000] {subprocess.py:93} INFO - [0m00:12:27  12 of 18 START test not_null_rsi_trade_date .................................... [RUN]
[2025-04-24T00:12:28.428+0000] {subprocess.py:93} INFO - [0m00:12:28  12 of 18 PASS not_null_rsi_trade_date .......................................... [[32mPASS[0m in 0.43s]
[2025-04-24T00:12:28.431+0000] {subprocess.py:93} INFO - [0m00:12:28  13 of 18 START test not_null_stock_indicators_rsi_14d .......................... [RUN]
[2025-04-24T00:12:28.945+0000] {subprocess.py:93} INFO - [0m00:12:28  13 of 18 PASS not_null_stock_indicators_rsi_14d ................................ [[32mPASS[0m in 0.51s]
[2025-04-24T00:12:28.949+0000] {subprocess.py:93} INFO - [0m00:12:28  14 of 18 START test not_null_stock_indicators_symbol ........................... [RUN]
[2025-04-24T00:12:29.510+0000] {subprocess.py:93} INFO - [0m00:12:29  14 of 18 PASS not_null_stock_indicators_symbol ................................. [[32mPASS[0m in 0.56s]
[2025-04-24T00:12:29.513+0000] {subprocess.py:93} INFO - [0m00:12:29  15 of 18 START test not_null_stock_indicators_trade_date ....................... [RUN]
[2025-04-24T00:12:30.003+0000] {subprocess.py:93} INFO - [0m00:12:30  15 of 18 PASS not_null_stock_indicators_trade_date ............................. [[32mPASS[0m in 0.49s]
[2025-04-24T00:12:30.007+0000] {subprocess.py:93} INFO - [0m00:12:30  16 of 18 START test not_null_volume_summary_symbol ............................. [RUN]
[2025-04-24T00:12:30.531+0000] {subprocess.py:93} INFO - [0m00:12:30  16 of 18 PASS not_null_volume_summary_symbol ................................... [[32mPASS[0m in 0.52s]
[2025-04-24T00:12:30.536+0000] {subprocess.py:93} INFO - [0m00:12:30  17 of 18 START test not_null_volume_summary_total_volume ....................... [RUN]
[2025-04-24T00:12:31.266+0000] {subprocess.py:93} INFO - [0m00:12:31  17 of 18 PASS not_null_volume_summary_total_volume ............................. [[32mPASS[0m in 0.73s]
[2025-04-24T00:12:31.271+0000] {subprocess.py:93} INFO - [0m00:12:31  18 of 18 START test not_null_volume_summary_trade_date ......................... [RUN]
[2025-04-24T00:12:31.758+0000] {subprocess.py:93} INFO - [0m00:12:31  18 of 18 PASS not_null_volume_summary_trade_date ............................... [[32mPASS[0m in 0.49s]
[2025-04-24T00:12:31.764+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.765+0000] {subprocess.py:93} INFO - [0m00:12:31  Finished running 18 data tests in 0 hours 0 minutes and 9.16 seconds (9.16s).
[2025-04-24T00:12:31.965+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.966+0000] {subprocess.py:93} INFO - [0m00:12:31  [31mCompleted with 5 errors and 0 warnings:[0m
[2025-04-24T00:12:31.968+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.970+0000] {subprocess.py:93} INFO - [0m00:12:31    Compilation Error in test dbt_utils_unique_combination_of_columns_moving_averages_symbol__trade_date (models/output/schema.yml)
[2025-04-24T00:12:31.971+0000] {subprocess.py:93} INFO -   'dbt_utils' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:12:31.972+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.973+0000] {subprocess.py:93} INFO - [0m00:12:31    Compilation Error in test dbt_utils_unique_combination_of_columns_rsi_symbol__trade_date (models/output/schema.yml)
[2025-04-24T00:12:31.975+0000] {subprocess.py:93} INFO -   'dbt_utils' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:12:31.976+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.976+0000] {subprocess.py:93} INFO - [0m00:12:31    Compilation Error in test dbt_utils_unique_combination_of_columns_stock_indicators_symbol__trade_date (models/output/schema.yml)
[2025-04-24T00:12:31.977+0000] {subprocess.py:93} INFO -   'dbt_utils' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:12:31.978+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.979+0000] {subprocess.py:93} INFO - [0m00:12:31    Compilation Error in test dbt_utils_unique_combination_of_columns_volume_summary_symbol__trade_date (models/output/schema.yml)
[2025-04-24T00:12:31.980+0000] {subprocess.py:93} INFO -   'dbt_utils' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:12:31.981+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.982+0000] {subprocess.py:93} INFO - [0m00:12:31  [31mFailure in test not_null_rsi_rsi_14d (models/output/schema.yml)[0m
[2025-04-24T00:12:31.983+0000] {subprocess.py:93} INFO - [0m00:12:31    Got 3 results, configured to fail if != 0
[2025-04-24T00:12:31.984+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.985+0000] {subprocess.py:93} INFO - [0m00:12:31    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/not_null_rsi_rsi_14d.sql
[2025-04-24T00:12:31.986+0000] {subprocess.py:93} INFO - [0m00:12:31
[2025-04-24T00:12:31.987+0000] {subprocess.py:93} INFO - [0m00:12:31  Done. PASS=13 WARN=0 ERROR=5 SKIP=0 TOTAL=18
[2025-04-24T00:12:32.665+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T00:12:32.676+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:12:32.680+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T00:12:04.746733+00:00, execution_date=20250424T001204, start_date=20250424T001219, end_date=20250424T001232
[2025-04-24T00:12:32.694+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T00:12:32.695+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 327 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 6429)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:12:32.730+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T00:12:32.752+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T00:12:32.760+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
