[2025-04-24T07:57:16.954+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T07:57:16.973+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:57:00.289754+00:00 [queued]>
[2025-04-24T07:57:16.981+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:57:00.289754+00:00 [queued]>
[2025-04-24T07:57:16.984+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T07:57:16.998+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 07:57:00.289754+00:00
[2025-04-24T07:57:17.007+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T07:57:00.289754+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmpnhsblvbd']
[2025-04-24T07:57:17.010+0000] {standard_task_runner.py:105} INFO - Job 367: Subtask dbt_test
[2025-04-24T07:57:17.010+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3717) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T07:57:17.012+0000] {standard_task_runner.py:72} INFO - Started process 3718 to run task
[2025-04-24T07:57:17.057+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T07:57:00.289754+00:00 [running]> on host e8b5346887eb
[2025-04-24T07:57:17.145+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T07:57:00.289754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T07:57:00.289754+00:00'
[2025-04-24T07:57:17.146+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T07:57:17.163+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T07:57:17.165+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T07:57:17.175+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T07:57:18.935+0000] {subprocess.py:93} INFO - [0m07:57:18  Running with dbt=1.8.7
[2025-04-24T07:57:20.035+0000] {subprocess.py:93} INFO - [0m07:57:20  Registered adapter: snowflake=1.8.1
[2025-04-24T07:57:20.749+0000] {subprocess.py:93} INFO - [0m07:57:20  Found 7 models, 11 data tests, 3 sources, 459 macros
[2025-04-24T07:57:20.754+0000] {subprocess.py:93} INFO - [0m07:57:20
[2025-04-24T07:57:21.573+0000] {subprocess.py:93} INFO - [0m07:57:21  Concurrency: 1 threads (target='dev')
[2025-04-24T07:57:21.575+0000] {subprocess.py:93} INFO - [0m07:57:21
[2025-04-24T07:57:21.586+0000] {subprocess.py:93} INFO - [0m07:57:21  1 of 11 START test not_null_moving_averages_stock_id ........................... [RUN]
[2025-04-24T07:57:22.563+0000] {subprocess.py:93} INFO - [0m07:57:22  1 of 11 PASS not_null_moving_averages_stock_id ................................. [[32mPASS[0m in 0.97s]
[2025-04-24T07:57:22.567+0000] {subprocess.py:93} INFO - [0m07:57:22  2 of 11 START test not_null_rsi_stock_id ....................................... [RUN]
[2025-04-24T07:57:23.316+0000] {subprocess.py:93} INFO - [0m07:57:23  2 of 11 PASS not_null_rsi_stock_id ............................................. [[32mPASS[0m in 0.75s]
[2025-04-24T07:57:23.319+0000] {subprocess.py:93} INFO - [0m07:57:23  3 of 11 START test not_null_stock_stock_id ..................................... [RUN]
[2025-04-24T07:57:23.929+0000] {subprocess.py:93} INFO - [0m07:57:23  3 of 11 PASS not_null_stock_stock_id ........................................... [[32mPASS[0m in 0.61s]
[2025-04-24T07:57:23.934+0000] {subprocess.py:93} INFO - [0m07:57:23  4 of 11 START test not_null_stock_symbol ....................................... [RUN]
[2025-04-24T07:57:24.627+0000] {subprocess.py:93} INFO - [0m07:57:24  4 of 11 PASS not_null_stock_symbol ............................................. [[32mPASS[0m in 0.69s]
[2025-04-24T07:57:24.629+0000] {subprocess.py:93} INFO - [0m07:57:24  5 of 11 START test not_null_stock_trade_date ................................... [RUN]
[2025-04-24T07:57:25.343+0000] {subprocess.py:93} INFO - [0m07:57:25  5 of 11 PASS not_null_stock_trade_date ......................................... [[32mPASS[0m in 0.71s]
[2025-04-24T07:57:25.347+0000] {subprocess.py:93} INFO - [0m07:57:25  6 of 11 START test relationships_moving_averages_stock_id__stock_id__ref_stock_  [RUN]
[2025-04-24T07:57:26.211+0000] {subprocess.py:93} INFO - [0m07:57:26  6 of 11 PASS relationships_moving_averages_stock_id__stock_id__ref_stock_ ...... [[32mPASS[0m in 0.86s]
[2025-04-24T07:57:26.215+0000] {subprocess.py:93} INFO - [0m07:57:26  7 of 11 START test relationships_rsi_stock_id__stock_id__ref_stock_ ............ [RUN]
[2025-04-24T07:57:27.011+0000] {subprocess.py:93} INFO - [0m07:57:27  7 of 11 PASS relationships_rsi_stock_id__stock_id__ref_stock_ .................. [[32mPASS[0m in 0.79s]
[2025-04-24T07:57:27.016+0000] {subprocess.py:93} INFO - [0m07:57:27  8 of 11 START test rsi_test .................................................... [RUN]
[2025-04-24T07:57:27.680+0000] {subprocess.py:93} INFO - [0m07:57:27  8 of 11 FAIL 18 rsi_test ....................................................... [[31mFAIL 18[0m in 0.66s]
[2025-04-24T07:57:27.683+0000] {subprocess.py:93} INFO - [0m07:57:27  9 of 11 START test unique_moving_averages_stock_id ............................. [RUN]
[2025-04-24T07:57:28.383+0000] {subprocess.py:93} INFO - [0m07:57:28  9 of 11 PASS unique_moving_averages_stock_id ................................... [[32mPASS[0m in 0.70s]
[2025-04-24T07:57:28.388+0000] {subprocess.py:93} INFO - [0m07:57:28  10 of 11 START test unique_rsi_stock_id ........................................ [RUN]
[2025-04-24T07:57:29.388+0000] {subprocess.py:93} INFO - [0m07:57:29  10 of 11 PASS unique_rsi_stock_id .............................................. [[32mPASS[0m in 1.00s]
[2025-04-24T07:57:29.390+0000] {subprocess.py:93} INFO - [0m07:57:29  11 of 11 START test unique_stock_stock_id ...................................... [RUN]
[2025-04-24T07:57:29.950+0000] {subprocess.py:93} INFO - [0m07:57:29  11 of 11 PASS unique_stock_stock_id ............................................ [[32mPASS[0m in 0.56s]
[2025-04-24T07:57:29.957+0000] {subprocess.py:93} INFO - [0m07:57:29
[2025-04-24T07:57:29.958+0000] {subprocess.py:93} INFO - [0m07:57:29  Finished running 11 data tests in 0 hours 0 minutes and 9.20 seconds (9.20s).
[2025-04-24T07:57:30.082+0000] {subprocess.py:93} INFO - [0m07:57:30
[2025-04-24T07:57:30.083+0000] {subprocess.py:93} INFO - [0m07:57:30  [31mCompleted with 1 error and 0 warnings:[0m
[2025-04-24T07:57:30.084+0000] {subprocess.py:93} INFO - [0m07:57:30
[2025-04-24T07:57:30.086+0000] {subprocess.py:93} INFO - [0m07:57:30  [31mFailure in test rsi_test (tests/rsi_test.sql)[0m
[2025-04-24T07:57:30.087+0000] {subprocess.py:93} INFO - [0m07:57:30    Got 18 results, configured to fail if != 0
[2025-04-24T07:57:30.088+0000] {subprocess.py:93} INFO - [0m07:57:30
[2025-04-24T07:57:30.089+0000] {subprocess.py:93} INFO - [0m07:57:30    compiled code at target/compiled/dbt_stock_project/tests/rsi_test.sql
[2025-04-24T07:57:30.090+0000] {subprocess.py:93} INFO - [0m07:57:30
[2025-04-24T07:57:30.091+0000] {subprocess.py:93} INFO - [0m07:57:30  Done. PASS=10 WARN=0 ERROR=1 SKIP=0 TOTAL=11
[2025-04-24T07:57:30.878+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T07:57:30.890+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T07:57:30.900+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T07:57:00.289754+00:00, execution_date=20250424T075700, start_date=20250424T075716, end_date=20250424T075730
[2025-04-24T07:57:30.913+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T07:57:30.914+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 367 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 3718)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T07:57:30.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T07:57:30.971+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T07:57:30.977+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
