[2025-04-22T15:20:15.709+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T15:20:15.727+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-22T15:19:41.305296+00:00 [queued]>
[2025-04-22T15:20:15.737+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-22T15:19:41.305296+00:00 [queued]>
[2025-04-22T15:20:15.740+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-22T15:20:15.753+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-04-22 15:19:41.305296+00:00
[2025-04-22T15:20:15.760+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_snapshot', 'manual__2025-04-22T15:19:41.305296+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmpngdbuhl1']
[2025-04-22T15:20:15.763+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=404) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T15:20:15.763+0000] {standard_task_runner.py:105} INFO - Job 283: Subtask dbt_snapshot
[2025-04-22T15:20:15.764+0000] {standard_task_runner.py:72} INFO - Started process 405 to run task
[2025-04-22T15:20:15.821+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_snapshot manual__2025-04-22T15:19:41.305296+00:00 [running]> on host 9d71c5fa265e
[2025-04-22T15:20:15.916+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T15:19:41.305296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T15:19:41.305296+00:00'
[2025-04-22T15:20:15.917+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-22T15:20:15.936+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T15:20:15.938+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-22T15:20:15.950+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T15:20:17.962+0000] {subprocess.py:93} INFO - [0m15:20:17  Running with dbt=1.8.7
[2025-04-22T15:20:19.006+0000] {subprocess.py:93} INFO - [0m15:20:19  Registered adapter: snowflake=1.8.1
[2025-04-22T15:20:19.766+0000] {subprocess.py:93} INFO - [0m15:20:19  Found 5 models, 9 data tests, 3 sources, 459 macros
[2025-04-22T15:20:19.770+0000] {subprocess.py:93} INFO - [0m15:20:19
[2025-04-22T15:20:19.772+0000] {subprocess.py:93} INFO - [0m15:20:19  Nothing to do. Try checking your model configs and model specification args
[2025-04-22T15:20:20.829+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-22T15:20:20.861+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-22T15:20:20.862+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_stock_project, task_id=dbt_snapshot, run_id=manual__2025-04-22T15:19:41.305296+00:00, execution_date=20250422T151941, start_date=20250422T152015, end_date=20250422T152020
[2025-04-22T15:20:20.898+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T15:20:20.915+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T15:20:20.918+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
