[2025-04-24T00:00:01.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:00:01.301+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T00:00:01.309+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T00:00:01.311+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T00:00:01.325+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train> on 2025-04-23 00:00:00+00:00
[2025-04-24T00:00:01.333+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5726) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T00:00:01.335+0000] {standard_task_runner.py:72} INFO - Started process 5731 to run task
[2025-04-24T00:00:01.334+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'train', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_train_predict.py', '--cfg-path', '/tmp/tmpct_d0b72']
[2025-04-24T00:00:01.337+0000] {standard_task_runner.py:105} INFO - Job 318: Subtask train
[2025-04-24T00:00:01.389+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [running]> on host d01273b1fd04
[2025-04-24T00:00:01.469+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T00:00:01.471+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:00:01.485+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-24T00:00:01.487+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-24T00:00:01.489+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T00:00:01.490+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T00:00:02.362+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T00:02:01.867+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T00:02:03.371+0000] {cursor.py:1156} INFO - Number of results in first chunk: 21
[2025-04-24T00:02:03.373+0000] {connection.py:788} INFO - closed
[2025-04-24T00:02:03.415+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-04-24T00:02:03.463+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T00:02:03.474+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T00:02:03.475+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_price_prediction, task_id=train, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T000001, end_date=20250424T000203
[2025-04-24T00:02:03.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T00:02:03.542+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-24T00:02:03.548+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-24T19:08:59.092+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T19:08:59.108+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T19:08:59.116+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T19:08:59.117+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T19:08:59.129+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train> on 2025-04-23 00:00:00+00:00
[2025-04-24T19:08:59.137+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1283) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T19:08:59.139+0000] {standard_task_runner.py:72} INFO - Started process 1289 to run task
[2025-04-24T19:08:59.137+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'train', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_train_predict.py', '--cfg-path', '/tmp/tmp0lnh1yih']
[2025-04-24T19:08:59.141+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask train
[2025-04-24T19:08:59.197+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [running]> on host 463df1d38e6b
[2025-04-24T19:08:59.275+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T19:08:59.277+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T19:08:59.288+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-24T19:08:59.290+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-24T19:08:59.292+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T19:08:59.293+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T19:08:59.719+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/226_lab1_train_predict.py", line 29, in train
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 300, in get_conn
    conn = connector.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 456, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 771, in connect
    self.__open_connection()
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1099, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1386, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1414, in _authenticate
    auth.authenticate(
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/auth/_auth.py", line 401, in authenticate
    Error.errorhandler_wrapper(
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 342, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.DatabaseError: 250001 (08001): None: Failed to connect to DB: SFEDU02-KSB65579.snowflakecomputing.com:443. Incorrect username or password was specified.
[2025-04-24T19:08:59.734+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=train, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T190859, end_date=20250424T190859
[2025-04-24T19:08:59.750+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T19:08:59.751+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task train (250001 (08001): None: Failed to connect to DB: SFEDU02-KSB65579.snowflakecomputing.com:443. Incorrect username or password was specified.; 1289)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/226_lab1_train_predict.py", line 29, in train
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 300, in get_conn
    conn = connector.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 456, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 771, in connect
    self.__open_connection()
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1099, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1386, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 1414, in _authenticate
    auth.authenticate(
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/auth/_auth.py", line 401, in authenticate
    Error.errorhandler_wrapper(
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 342, in hand_to_other_handler
    connection.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.DatabaseError: 250001 (08001): None: Failed to connect to DB: SFEDU02-KSB65579.snowflakecomputing.com:443. Incorrect username or password was specified.
[2025-04-24T19:08:59.792+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T19:08:59.811+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T19:08:59.814+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-24T20:14:52.797+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T20:14:52.825+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T20:14:52.838+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T20:14:52.839+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T20:14:52.858+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train> on 2025-04-23 00:00:00+00:00
[2025-04-24T20:14:52.869+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1255) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T20:14:52.871+0000] {standard_task_runner.py:72} INFO - Started process 1261 to run task
[2025-04-24T20:14:52.870+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'train', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_train_predict.py', '--cfg-path', '/tmp/tmpoexckir5']
[2025-04-24T20:14:52.874+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask train
[2025-04-24T20:14:52.945+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_prediction.train scheduled__2025-04-23T00:00:00+00:00 [running]> on host 785c12b0fea3
[2025-04-24T20:14:53.066+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T20:14:53.068+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T20:14:53.082+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-24T20:14:53.083+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-24T20:14:53.085+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T20:14:53.086+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T20:14:54.054+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T20:17:02.425+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T20:17:04.033+0000] {cursor.py:1156} INFO - Number of results in first chunk: 21
[2025-04-24T20:17:04.034+0000] {connection.py:788} INFO - closed
[2025-04-24T20:17:04.097+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-04-24T20:17:04.177+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-24T20:17:04.193+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T20:17:04.194+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_price_prediction, task_id=train, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T201452, end_date=20250424T201704
[2025-04-24T20:17:04.223+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-24T20:17:04.243+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-24T20:17:04.246+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
