[2025-04-23T23:07:33.300+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T23:07:33.320+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 226_lab1_etl.load manual__2025-04-23T23:07:28.086377+00:00 [queued]>
[2025-04-23T23:07:33.333+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 226_lab1_etl.load manual__2025-04-23T23:07:28.086377+00:00 [queued]>
[2025-04-23T23:07:33.334+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-23T23:07:33.353+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-04-23 23:07:28.086377+00:00
[2025-04-23T23:07:33.364+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '226_lab1_etl', 'load', 'manual__2025-04-23T23:07:28.086377+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/226_lab1_etl.py', '--cfg-path', '/tmp/tmps5vsgkak']
[2025-04-23T23:07:33.368+0000] {standard_task_runner.py:105} INFO - Job 305: Subtask load
[2025-04-23T23:07:33.368+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T23:07:33.369+0000] {standard_task_runner.py:72} INFO - Started process 3207 to run task
[2025-04-23T23:07:33.430+0000] {task_command.py:467} INFO - Running <TaskInstance: 226_lab1_etl.load manual__2025-04-23T23:07:28.086377+00:00 [running]> on host d01273b1fd04
[2025-04-23T23:07:33.551+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='226_lab1_etl' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T23:07:28.086377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T23:07:28.086377+00:00'
[2025-04-23T23:07:33.553+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T23:07:33.574+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-23T23:07:33.576+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-23T23:07:33.577+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T23:07:34.312+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-23T23:07:34.430+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-23T23:12:59.782+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-23T23:12:59.784+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T23:12:59.796+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T23:12:59.798+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=226_lab1_etl, task_id=load, run_id=manual__2025-04-23T23:07:28.086377+00:00, execution_date=20250423T230728, start_date=20250423T230733, end_date=20250423T231259
[2025-04-23T23:12:59.904+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T23:12:59.918+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T23:12:59.940+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
