[2025-04-24T00:41:42.186+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:41:42.206+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:41:29.206969+00:00 [queued]>
[2025-04-24T00:41:42.214+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:41:29.206969+00:00 [queued]>
[2025-04-24T00:41:42.216+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T00:41:42.229+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 00:41:29.206969+00:00
[2025-04-24T00:41:42.238+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8080) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T00:41:42.237+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T00:41:29.206969+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmprowbjsdw']
[2025-04-24T00:41:42.240+0000] {standard_task_runner.py:72} INFO - Started process 8081 to run task
[2025-04-24T00:41:42.241+0000] {standard_task_runner.py:105} INFO - Job 339: Subtask dbt_test
[2025-04-24T00:41:42.291+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:41:29.206969+00:00 [running]> on host d01273b1fd04
[2025-04-24T00:41:42.368+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T00:41:29.206969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T00:41:29.206969+00:00'
[2025-04-24T00:41:42.370+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:41:42.382+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T00:41:42.385+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T00:41:42.394+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T00:41:44.297+0000] {subprocess.py:93} INFO - [0m00:41:44  Running with dbt=1.8.7
[2025-04-24T00:41:45.295+0000] {subprocess.py:93} INFO - [0m00:41:45  Registered adapter: snowflake=1.8.1
[2025-04-24T00:41:46.173+0000] {subprocess.py:93} INFO - [0m00:41:46  Found 6 models, 22 data tests, 3 sources, 459 macros
[2025-04-24T00:41:46.177+0000] {subprocess.py:93} INFO - [0m00:41:46
[2025-04-24T00:41:46.790+0000] {subprocess.py:93} INFO - [0m00:41:46  Concurrency: 1 threads (target='dev')
[2025-04-24T00:41:46.791+0000] {subprocess.py:93} INFO - [0m00:41:46
[2025-04-24T00:41:46.804+0000] {subprocess.py:93} INFO - [0m00:41:46  1 of 22 START test not_null_moving_averages_close_price_14d_ma ................. [RUN]
[2025-04-24T00:41:47.499+0000] {subprocess.py:93} INFO - [0m00:41:47  1 of 22 FAIL 21 not_null_moving_averages_close_price_14d_ma .................... [[31mFAIL 21[0m in 0.69s]
[2025-04-24T00:41:47.503+0000] {subprocess.py:93} INFO - [0m00:41:47  2 of 22 START test not_null_moving_averages_close_price_30d_ma ................. [RUN]
[2025-04-24T00:41:48.056+0000] {subprocess.py:93} INFO - [0m00:41:48  2 of 22 FAIL 69 not_null_moving_averages_close_price_30d_ma .................... [[31mFAIL 69[0m in 0.55s]
[2025-04-24T00:41:48.060+0000] {subprocess.py:93} INFO - [0m00:41:48  3 of 22 START test not_null_moving_averages_close_price_7d_ma .................. [RUN]
[2025-04-24T00:41:48.697+0000] {subprocess.py:93} INFO - [0m00:41:48  3 of 22 PASS not_null_moving_averages_close_price_7d_ma ........................ [[32mPASS[0m in 0.64s]
[2025-04-24T00:41:48.702+0000] {subprocess.py:93} INFO - [0m00:41:48  4 of 22 START test not_null_moving_averages_symbol ............................. [RUN]
[2025-04-24T00:41:49.348+0000] {subprocess.py:93} INFO - [0m00:41:49  4 of 22 PASS not_null_moving_averages_symbol ................................... [[32mPASS[0m in 0.64s]
[2025-04-24T00:41:49.354+0000] {subprocess.py:93} INFO - [0m00:41:49  5 of 22 START test not_null_moving_averages_trade_date ......................... [RUN]
[2025-04-24T00:41:49.927+0000] {subprocess.py:93} INFO - [0m00:41:49  5 of 22 PASS not_null_moving_averages_trade_date ............................... [[32mPASS[0m in 0.57s]
[2025-04-24T00:41:49.930+0000] {subprocess.py:93} INFO - [0m00:41:49  6 of 22 START test not_null_rsi_rsi_14d ........................................ [RUN]
[2025-04-24T00:41:50.544+0000] {subprocess.py:93} INFO - [0m00:41:50  6 of 22 PASS not_null_rsi_rsi_14d .............................................. [[32mPASS[0m in 0.61s]
[2025-04-24T00:41:50.546+0000] {subprocess.py:93} INFO - [0m00:41:50  7 of 22 START test not_null_rsi_symbol ......................................... [RUN]
[2025-04-24T00:41:51.070+0000] {subprocess.py:93} INFO - [0m00:41:51  7 of 22 PASS not_null_rsi_symbol ............................................... [[32mPASS[0m in 0.52s]
[2025-04-24T00:41:51.074+0000] {subprocess.py:93} INFO - [0m00:41:51  8 of 22 START test not_null_rsi_trade_date ..................................... [RUN]
[2025-04-24T00:41:51.627+0000] {subprocess.py:93} INFO - [0m00:41:51  8 of 22 PASS not_null_rsi_trade_date ........................................... [[32mPASS[0m in 0.55s]
[2025-04-24T00:41:51.632+0000] {subprocess.py:93} INFO - [0m00:41:51  9 of 22 START test not_null_stock_indicators_rsi_14d ........................... [RUN]
[2025-04-24T00:41:52.171+0000] {subprocess.py:93} INFO - [0m00:41:52  9 of 22 ERROR not_null_stock_indicators_rsi_14d ................................ [[31mERROR[0m in 0.54s]
[2025-04-24T00:41:52.175+0000] {subprocess.py:93} INFO - [0m00:41:52  10 of 22 START test not_null_stock_indicators_symbol ........................... [RUN]
[2025-04-24T00:41:52.805+0000] {subprocess.py:93} INFO - [0m00:41:52  10 of 22 PASS not_null_stock_indicators_symbol ................................. [[32mPASS[0m in 0.63s]
[2025-04-24T00:41:52.808+0000] {subprocess.py:93} INFO - [0m00:41:52  11 of 22 START test not_null_stock_indicators_trade_date ....................... [RUN]
[2025-04-24T00:41:53.305+0000] {subprocess.py:93} INFO - [0m00:41:53  11 of 22 PASS not_null_stock_indicators_trade_date ............................. [[32mPASS[0m in 0.49s]
[2025-04-24T00:41:53.311+0000] {subprocess.py:93} INFO - [0m00:41:53  12 of 22 START test not_null_volume_summary_symbol ............................. [RUN]
[2025-04-24T00:41:53.876+0000] {subprocess.py:93} INFO - [0m00:41:53  12 of 22 PASS not_null_volume_summary_symbol ................................... [[32mPASS[0m in 0.56s]
[2025-04-24T00:41:53.879+0000] {subprocess.py:93} INFO - [0m00:41:53  13 of 22 START test not_null_volume_summary_total_volume ....................... [RUN]
[2025-04-24T00:41:54.341+0000] {subprocess.py:93} INFO - [0m00:41:54  13 of 22 ERROR not_null_volume_summary_total_volume ............................ [[31mERROR[0m in 0.46s]
[2025-04-24T00:41:54.345+0000] {subprocess.py:93} INFO - [0m00:41:54  14 of 22 START test not_null_volume_summary_trade_date ......................... [RUN]
[2025-04-24T00:41:54.888+0000] {subprocess.py:93} INFO - [0m00:41:54  14 of 22 PASS not_null_volume_summary_trade_date ............................... [[32mPASS[0m in 0.54s]
[2025-04-24T00:41:54.892+0000] {subprocess.py:93} INFO - [0m00:41:54  15 of 22 START test positive_values_moving_averages_close_price_14d_ma ......... [RUN]
[2025-04-24T00:41:54.905+0000] {subprocess.py:93} INFO - [0m00:41:54  15 of 22 ERROR positive_values_moving_averages_close_price_14d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-24T00:41:54.908+0000] {subprocess.py:93} INFO - [0m00:41:54  16 of 22 START test positive_values_moving_averages_close_price_30d_ma ......... [RUN]
[2025-04-24T00:41:54.919+0000] {subprocess.py:93} INFO - [0m00:41:54  16 of 22 ERROR positive_values_moving_averages_close_price_30d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-24T00:41:54.922+0000] {subprocess.py:93} INFO - [0m00:41:54  17 of 22 START test positive_values_moving_averages_close_price_7d_ma .......... [RUN]
[2025-04-24T00:41:54.932+0000] {subprocess.py:93} INFO - [0m00:41:54  17 of 22 ERROR positive_values_moving_averages_close_price_7d_ma ............... [[31mERROR[0m in 0.01s]
[2025-04-24T00:41:54.936+0000] {subprocess.py:93} INFO - [0m00:41:54  18 of 22 START test range_rsi_rsi_14d__100__0 .................................. [RUN]
[2025-04-24T00:41:54.945+0000] {subprocess.py:93} INFO - [0m00:41:54  18 of 22 ERROR range_rsi_rsi_14d__100__0 ....................................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:41:54.949+0000] {subprocess.py:93} INFO - [0m00:41:54  19 of 22 START test range_stock_indicators_rsi_14d__100__0 ..................... [RUN]
[2025-04-24T00:41:54.958+0000] {subprocess.py:93} INFO - [0m00:41:54  19 of 22 ERROR range_stock_indicators_rsi_14d__100__0 .......................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:41:54.962+0000] {subprocess.py:93} INFO - [0m00:41:54  20 of 22 START test relationships_moving_averages_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-24T00:41:55.653+0000] {subprocess.py:93} INFO - [0m00:41:55  20 of 22 PASS relationships_moving_averages_symbol__symbol__source_raw_stock_ .. [[32mPASS[0m in 0.69s]
[2025-04-24T00:41:55.657+0000] {subprocess.py:93} INFO - [0m00:41:55  21 of 22 START test relationships_rsi_symbol__symbol__source_raw_stock_ ........ [RUN]
[2025-04-24T00:41:56.354+0000] {subprocess.py:93} INFO - [0m00:41:56  21 of 22 PASS relationships_rsi_symbol__symbol__source_raw_stock_ .............. [[32mPASS[0m in 0.70s]
[2025-04-24T00:41:56.358+0000] {subprocess.py:93} INFO - [0m00:41:56  22 of 22 START test relationships_stock_indicators_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-24T00:41:56.965+0000] {subprocess.py:93} INFO - [0m00:41:56  22 of 22 PASS relationships_stock_indicators_symbol__symbol__source_raw_stock_ . [[32mPASS[0m in 0.61s]
[2025-04-24T00:41:56.972+0000] {subprocess.py:93} INFO - [0m00:41:56
[2025-04-24T00:41:56.973+0000] {subprocess.py:93} INFO - [0m00:41:56  Finished running 22 data tests in 0 hours 0 minutes and 10.79 seconds (10.79s).
[2025-04-24T00:41:57.078+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.079+0000] {subprocess.py:93} INFO - [0m00:41:57  [31mCompleted with 9 errors and 0 warnings:[0m
[2025-04-24T00:41:57.080+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.081+0000] {subprocess.py:93} INFO - [0m00:41:57  [31mFailure in test not_null_moving_averages_close_price_14d_ma (models/output/schema.yml)[0m
[2025-04-24T00:41:57.081+0000] {subprocess.py:93} INFO - [0m00:41:57    Got 21 results, configured to fail if != 0
[2025-04-24T00:41:57.082+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.083+0000] {subprocess.py:93} INFO - [0m00:41:57    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/not_null_moving_averages_close_price_14d_ma.sql
[2025-04-24T00:41:57.084+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.086+0000] {subprocess.py:93} INFO - [0m00:41:57  [31mFailure in test not_null_moving_averages_close_price_30d_ma (models/output/schema.yml)[0m
[2025-04-24T00:41:57.087+0000] {subprocess.py:93} INFO - [0m00:41:57    Got 69 results, configured to fail if != 0
[2025-04-24T00:41:57.087+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.088+0000] {subprocess.py:93} INFO - [0m00:41:57    compiled code at target/compiled/dbt_stock_project/models/output/schema.yml/not_null_moving_averages_close_price_30d_ma.sql
[2025-04-24T00:41:57.089+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.089+0000] {subprocess.py:93} INFO - [0m00:41:57    Database Error in test not_null_stock_indicators_rsi_14d (models/output/schema.yml)
[2025-04-24T00:41:57.090+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-24T00:41:57.090+0000] {subprocess.py:93} INFO -   invalid identifier 'RSI_14D'
[2025-04-24T00:41:57.091+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_stock_indicators_rsi_14d.sql
[2025-04-24T00:41:57.091+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.092+0000] {subprocess.py:93} INFO - [0m00:41:57    Database Error in test not_null_volume_summary_total_volume (models/output/schema.yml)
[2025-04-24T00:41:57.092+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-24T00:41:57.093+0000] {subprocess.py:93} INFO -   invalid identifier 'TOTAL_VOLUME'
[2025-04-24T00:41:57.093+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_volume_summary_total_volume.sql
[2025-04-24T00:41:57.094+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.094+0000] {subprocess.py:93} INFO - [0m00:41:57    Compilation Error in test positive_values_moving_averages_close_price_14d_ma (models/output/schema.yml)
[2025-04-24T00:41:57.094+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:41:57.094+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.095+0000] {subprocess.py:93} INFO - [0m00:41:57    Compilation Error in test positive_values_moving_averages_close_price_30d_ma (models/output/schema.yml)
[2025-04-24T00:41:57.095+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:41:57.095+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.096+0000] {subprocess.py:93} INFO - [0m00:41:57    Compilation Error in test positive_values_moving_averages_close_price_7d_ma (models/output/schema.yml)
[2025-04-24T00:41:57.096+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:41:57.096+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.097+0000] {subprocess.py:93} INFO - [0m00:41:57    Compilation Error in test range_rsi_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T00:41:57.097+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:41:57.097+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.098+0000] {subprocess.py:93} INFO - [0m00:41:57    Compilation Error in test range_stock_indicators_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T00:41:57.098+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:41:57.099+0000] {subprocess.py:93} INFO - [0m00:41:57
[2025-04-24T00:41:57.100+0000] {subprocess.py:93} INFO - [0m00:41:57  Done. PASS=13 WARN=0 ERROR=9 SKIP=0 TOTAL=22
[2025-04-24T00:41:57.830+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T00:41:57.842+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:41:57.847+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T00:41:29.206969+00:00, execution_date=20250424T004129, start_date=20250424T004142, end_date=20250424T004157
[2025-04-24T00:41:57.863+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T00:41:57.864+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 339 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 8081)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:41:57.907+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T00:41:57.930+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T00:41:57.937+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
