[2025-04-24T00:34:28.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:34:29.003+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:34:13.478472+00:00 [queued]>
[2025-04-24T00:34:29.013+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:34:13.478472+00:00 [queued]>
[2025-04-24T00:34:29.015+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T00:34:29.029+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 00:34:13.478472+00:00
[2025-04-24T00:34:29.038+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7644) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T00:34:29.037+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T00:34:13.478472+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmpclcikcyp']
[2025-04-24T00:34:29.040+0000] {standard_task_runner.py:72} INFO - Started process 7645 to run task
[2025-04-24T00:34:29.040+0000] {standard_task_runner.py:105} INFO - Job 335: Subtask dbt_test
[2025-04-24T00:34:29.092+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:34:13.478472+00:00 [running]> on host d01273b1fd04
[2025-04-24T00:34:29.184+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T00:34:13.478472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T00:34:13.478472+00:00'
[2025-04-24T00:34:29.186+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:34:29.204+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T00:34:29.207+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T00:34:29.218+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T00:34:31.072+0000] {subprocess.py:93} INFO - [0m00:34:31  Running with dbt=1.8.7
[2025-04-24T00:34:31.976+0000] {subprocess.py:93} INFO - [0m00:34:31  Registered adapter: snowflake=1.8.1
[2025-04-24T00:34:32.872+0000] {subprocess.py:93} INFO - [0m00:34:32  Found 6 models, 23 data tests, 3 sources, 459 macros
[2025-04-24T00:34:32.877+0000] {subprocess.py:93} INFO - [0m00:34:32
[2025-04-24T00:34:33.473+0000] {subprocess.py:93} INFO - [0m00:34:33  Concurrency: 1 threads (target='dev')
[2025-04-24T00:34:33.474+0000] {subprocess.py:93} INFO - [0m00:34:33
[2025-04-24T00:34:33.485+0000] {subprocess.py:93} INFO - [0m00:34:33  1 of 23 START test not_null_moving_averages_close_price_14d_ma ................. [RUN]
[2025-04-24T00:34:34.096+0000] {subprocess.py:93} INFO - [0m00:34:34  1 of 23 PASS not_null_moving_averages_close_price_14d_ma ....................... [[32mPASS[0m in 0.61s]
[2025-04-24T00:34:34.099+0000] {subprocess.py:93} INFO - [0m00:34:34  2 of 23 START test not_null_moving_averages_close_price_30d_ma ................. [RUN]
[2025-04-24T00:34:34.511+0000] {subprocess.py:93} INFO - [0m00:34:34  2 of 23 PASS not_null_moving_averages_close_price_30d_ma ....................... [[32mPASS[0m in 0.41s]
[2025-04-24T00:34:34.514+0000] {subprocess.py:93} INFO - [0m00:34:34  3 of 23 START test not_null_moving_averages_close_price_7d_ma .................. [RUN]
[2025-04-24T00:34:35.100+0000] {subprocess.py:93} INFO - [0m00:34:35  3 of 23 PASS not_null_moving_averages_close_price_7d_ma ........................ [[32mPASS[0m in 0.58s]
[2025-04-24T00:34:35.104+0000] {subprocess.py:93} INFO - [0m00:34:35  4 of 23 START test not_null_moving_averages_symbol ............................. [RUN]
[2025-04-24T00:34:35.645+0000] {subprocess.py:93} INFO - [0m00:34:35  4 of 23 PASS not_null_moving_averages_symbol ................................... [[32mPASS[0m in 0.54s]
[2025-04-24T00:34:35.648+0000] {subprocess.py:93} INFO - [0m00:34:35  5 of 23 START test not_null_moving_averages_trade_date ......................... [RUN]
[2025-04-24T00:34:36.224+0000] {subprocess.py:93} INFO - [0m00:34:36  5 of 23 PASS not_null_moving_averages_trade_date ............................... [[32mPASS[0m in 0.57s]
[2025-04-24T00:34:36.227+0000] {subprocess.py:93} INFO - [0m00:34:36  6 of 23 START test not_null_rsi_rsi_14d ........................................ [RUN]
[2025-04-24T00:34:36.931+0000] {subprocess.py:93} INFO - [0m00:34:36  6 of 23 PASS not_null_rsi_rsi_14d .............................................. [[32mPASS[0m in 0.70s]
[2025-04-24T00:34:36.934+0000] {subprocess.py:93} INFO - [0m00:34:36  7 of 23 START test not_null_rsi_symbol ......................................... [RUN]
[2025-04-24T00:34:37.440+0000] {subprocess.py:93} INFO - [0m00:34:37  7 of 23 PASS not_null_rsi_symbol ............................................... [[32mPASS[0m in 0.50s]
[2025-04-24T00:34:37.446+0000] {subprocess.py:93} INFO - [0m00:34:37  8 of 23 START test not_null_rsi_trade_date ..................................... [RUN]
[2025-04-24T00:34:38.006+0000] {subprocess.py:93} INFO - [0m00:34:38  8 of 23 PASS not_null_rsi_trade_date ........................................... [[32mPASS[0m in 0.56s]
[2025-04-24T00:34:38.010+0000] {subprocess.py:93} INFO - [0m00:34:38  9 of 23 START test not_null_stock_indicators_rsi_14d ........................... [RUN]
[2025-04-24T00:34:38.546+0000] {subprocess.py:93} INFO - [0m00:34:38  9 of 23 ERROR not_null_stock_indicators_rsi_14d ................................ [[31mERROR[0m in 0.53s]
[2025-04-24T00:34:38.549+0000] {subprocess.py:93} INFO - [0m00:34:38  10 of 23 START test not_null_stock_indicators_symbol ........................... [RUN]
[2025-04-24T00:34:39.032+0000] {subprocess.py:93} INFO - [0m00:34:39  10 of 23 PASS not_null_stock_indicators_symbol ................................. [[32mPASS[0m in 0.48s]
[2025-04-24T00:34:39.035+0000] {subprocess.py:93} INFO - [0m00:34:39  11 of 23 START test not_null_stock_indicators_trade_date ....................... [RUN]
[2025-04-24T00:34:39.598+0000] {subprocess.py:93} INFO - [0m00:34:39  11 of 23 PASS not_null_stock_indicators_trade_date ............................. [[32mPASS[0m in 0.56s]
[2025-04-24T00:34:39.603+0000] {subprocess.py:93} INFO - [0m00:34:39  12 of 23 START test not_null_volume_summary_symbol ............................. [RUN]
[2025-04-24T00:34:40.162+0000] {subprocess.py:93} INFO - [0m00:34:40  12 of 23 PASS not_null_volume_summary_symbol ................................... [[32mPASS[0m in 0.56s]
[2025-04-24T00:34:40.166+0000] {subprocess.py:93} INFO - [0m00:34:40  13 of 23 START test not_null_volume_summary_total_volume ....................... [RUN]
[2025-04-24T00:34:40.637+0000] {subprocess.py:93} INFO - [0m00:34:40  13 of 23 ERROR not_null_volume_summary_total_volume ............................ [[31mERROR[0m in 0.47s]
[2025-04-24T00:34:40.640+0000] {subprocess.py:93} INFO - [0m00:34:40  14 of 23 START test not_null_volume_summary_trade_date ......................... [RUN]
[2025-04-24T00:34:41.232+0000] {subprocess.py:93} INFO - [0m00:34:41  14 of 23 PASS not_null_volume_summary_trade_date ............................... [[32mPASS[0m in 0.59s]
[2025-04-24T00:34:41.236+0000] {subprocess.py:93} INFO - [0m00:34:41  15 of 23 START test positive_values_moving_averages_close_price_14d_ma ......... [RUN]
[2025-04-24T00:34:41.251+0000] {subprocess.py:93} INFO - [0m00:34:41  15 of 23 ERROR positive_values_moving_averages_close_price_14d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-24T00:34:41.254+0000] {subprocess.py:93} INFO - [0m00:34:41  16 of 23 START test positive_values_moving_averages_close_price_30d_ma ......... [RUN]
[2025-04-24T00:34:41.265+0000] {subprocess.py:93} INFO - [0m00:34:41  16 of 23 ERROR positive_values_moving_averages_close_price_30d_ma .............. [[31mERROR[0m in 0.01s]
[2025-04-24T00:34:41.269+0000] {subprocess.py:93} INFO - [0m00:34:41  17 of 23 START test positive_values_moving_averages_close_price_7d_ma .......... [RUN]
[2025-04-24T00:34:41.278+0000] {subprocess.py:93} INFO - [0m00:34:41  17 of 23 ERROR positive_values_moving_averages_close_price_7d_ma ............... [[31mERROR[0m in 0.01s]
[2025-04-24T00:34:41.282+0000] {subprocess.py:93} INFO - [0m00:34:41  18 of 23 START test positive_values_volume_summary_total_volume ................ [RUN]
[2025-04-24T00:34:41.291+0000] {subprocess.py:93} INFO - [0m00:34:41  18 of 23 ERROR positive_values_volume_summary_total_volume ..................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:34:41.295+0000] {subprocess.py:93} INFO - [0m00:34:41  19 of 23 START test range_rsi_rsi_14d__100__0 .................................. [RUN]
[2025-04-24T00:34:41.304+0000] {subprocess.py:93} INFO - [0m00:34:41  19 of 23 ERROR range_rsi_rsi_14d__100__0 ....................................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:34:41.308+0000] {subprocess.py:93} INFO - [0m00:34:41  20 of 23 START test range_stock_indicators_rsi_14d__100__0 ..................... [RUN]
[2025-04-24T00:34:41.317+0000] {subprocess.py:93} INFO - [0m00:34:41  20 of 23 ERROR range_stock_indicators_rsi_14d__100__0 .......................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:34:41.321+0000] {subprocess.py:93} INFO - [0m00:34:41  21 of 23 START test relationships_moving_averages_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-24T00:34:41.955+0000] {subprocess.py:93} INFO - [0m00:34:41  21 of 23 PASS relationships_moving_averages_symbol__symbol__source_raw_stock_ .. [[32mPASS[0m in 0.63s]
[2025-04-24T00:34:41.959+0000] {subprocess.py:93} INFO - [0m00:34:41  22 of 23 START test relationships_rsi_symbol__symbol__source_raw_stock_ ........ [RUN]
[2025-04-24T00:34:42.686+0000] {subprocess.py:93} INFO - [0m00:34:42  22 of 23 PASS relationships_rsi_symbol__symbol__source_raw_stock_ .............. [[32mPASS[0m in 0.73s]
[2025-04-24T00:34:42.689+0000] {subprocess.py:93} INFO - [0m00:34:42  23 of 23 START test relationships_stock_indicators_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-24T00:34:43.210+0000] {subprocess.py:93} INFO - [0m00:34:43  23 of 23 PASS relationships_stock_indicators_symbol__symbol__source_raw_stock_ . [[32mPASS[0m in 0.52s]
[2025-04-24T00:34:43.216+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.217+0000] {subprocess.py:93} INFO - [0m00:34:43  Finished running 23 data tests in 0 hours 0 minutes and 10.34 seconds (10.34s).
[2025-04-24T00:34:43.343+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.344+0000] {subprocess.py:93} INFO - [0m00:34:43  [31mCompleted with 8 errors and 0 warnings:[0m
[2025-04-24T00:34:43.345+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.347+0000] {subprocess.py:93} INFO - [0m00:34:43    Database Error in test not_null_stock_indicators_rsi_14d (models/output/schema.yml)
[2025-04-24T00:34:43.348+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-24T00:34:43.350+0000] {subprocess.py:93} INFO -   invalid identifier 'RSI_14D'
[2025-04-24T00:34:43.351+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_stock_indicators_rsi_14d.sql
[2025-04-24T00:34:43.352+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.352+0000] {subprocess.py:93} INFO - [0m00:34:43    Database Error in test not_null_volume_summary_total_volume (models/output/schema.yml)
[2025-04-24T00:34:43.354+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-24T00:34:43.354+0000] {subprocess.py:93} INFO -   invalid identifier 'TOTAL_VOLUME'
[2025-04-24T00:34:43.355+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_volume_summary_total_volume.sql
[2025-04-24T00:34:43.356+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.356+0000] {subprocess.py:93} INFO - [0m00:34:43    Compilation Error in test positive_values_moving_averages_close_price_14d_ma (models/output/schema.yml)
[2025-04-24T00:34:43.357+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:34:43.357+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.358+0000] {subprocess.py:93} INFO - [0m00:34:43    Compilation Error in test positive_values_moving_averages_close_price_30d_ma (models/output/schema.yml)
[2025-04-24T00:34:43.359+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:34:43.360+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.361+0000] {subprocess.py:93} INFO - [0m00:34:43    Compilation Error in test positive_values_moving_averages_close_price_7d_ma (models/output/schema.yml)
[2025-04-24T00:34:43.362+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:34:43.363+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.363+0000] {subprocess.py:93} INFO - [0m00:34:43    Compilation Error in test positive_values_volume_summary_total_volume (models/output/schema.yml)
[2025-04-24T00:34:43.364+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:34:43.364+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.365+0000] {subprocess.py:93} INFO - [0m00:34:43    Compilation Error in test range_rsi_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T00:34:43.365+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:34:43.366+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.367+0000] {subprocess.py:93} INFO - [0m00:34:43    Compilation Error in test range_stock_indicators_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T00:34:43.367+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:34:43.368+0000] {subprocess.py:93} INFO - [0m00:34:43
[2025-04-24T00:34:43.369+0000] {subprocess.py:93} INFO - [0m00:34:43  Done. PASS=15 WARN=0 ERROR=8 SKIP=0 TOTAL=23
[2025-04-24T00:34:44.073+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T00:34:44.083+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:34:44.093+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T00:34:13.478472+00:00, execution_date=20250424T003413, start_date=20250424T003429, end_date=20250424T003444
[2025-04-24T00:34:44.108+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T00:34:44.109+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 335 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 7645)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:34:44.120+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T00:34:44.139+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T00:34:44.145+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
