[2025-04-24T07:32:15.933+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T07:32:15.950+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_run manual__2025-04-24T07:32:15.038612+00:00 [queued]>
[2025-04-24T07:32:15.959+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_run manual__2025-04-24T07:32:15.038612+00:00 [queued]>
[2025-04-24T07:32:15.961+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T07:32:15.977+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-04-24 07:32:15.038612+00:00
[2025-04-24T07:32:15.985+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_run', 'manual__2025-04-24T07:32:15.038612+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmpw5xv9dhl']
[2025-04-24T07:32:15.988+0000] {standard_task_runner.py:105} INFO - Job 357: Subtask dbt_run
[2025-04-24T07:32:15.988+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2325) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T07:32:15.990+0000] {standard_task_runner.py:72} INFO - Started process 2326 to run task
[2025-04-24T07:32:16.045+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_run manual__2025-04-24T07:32:15.038612+00:00 [running]> on host e8b5346887eb
[2025-04-24T07:32:16.131+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T07:32:15.038612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T07:32:15.038612+00:00'
[2025-04-24T07:32:16.133+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T07:32:16.147+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T07:32:16.149+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T07:32:16.159+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T07:32:17.998+0000] {subprocess.py:93} INFO - [0m07:32:17  Running with dbt=1.8.7
[2025-04-24T07:32:18.980+0000] {subprocess.py:93} INFO - [0m07:32:18  Registered adapter: snowflake=1.8.1
[2025-04-24T07:32:19.706+0000] {subprocess.py:93} INFO - [0m07:32:19  [[33mWARNING[0m]: Deprecated functionality
[2025-04-24T07:32:19.707+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2025-04-24T07:32:19.708+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2025-04-24T07:32:19.710+0000] {subprocess.py:93} INFO - information.
[2025-04-24T07:32:19.810+0000] {subprocess.py:93} INFO - [0m07:32:19  Encountered an error:
[2025-04-24T07:32:19.812+0000] {subprocess.py:93} INFO - Parsing Error
[2025-04-24T07:32:19.813+0000] {subprocess.py:93} INFO -   Invalid test config given in models/output/schema.yml:
[2025-04-24T07:32:19.814+0000] {subprocess.py:93} INFO -   	test definition dictionary must have exactly one key, got [('accepted_values', None), ('values', [0, 100]), ('strict', True)] instead (3 keys)
[2025-04-24T07:32:19.815+0000] {subprocess.py:93} INFO -   	@: UnparsedModelUpdate(original_file_path='mode...ne)
[2025-04-24T07:32:20.695+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-24T07:32:20.705+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-24T07:32:20.709+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_run, run_id=manual__2025-04-24T07:32:15.038612+00:00, execution_date=20250424T073215, start_date=20250424T073215, end_date=20250424T073220
[2025-04-24T07:32:20.723+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T07:32:20.724+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 357 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 2326)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-24T07:32:20.753+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T07:32:20.773+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T07:32:20.780+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
