[2025-04-24T00:50:51.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:50:51.918+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:50:37.125505+00:00 [queued]>
[2025-04-24T00:50:51.929+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:50:37.125505+00:00 [queued]>
[2025-04-24T00:50:51.930+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-24T00:50:51.945+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-24 00:50:37.125505+00:00
[2025-04-24T00:50:51.953+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_stock_project', 'dbt_test', 'manual__2025-04-24T00:50:37.125505+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/226_lab2_elt.py', '--cfg-path', '/tmp/tmpplzsaix8']
[2025-04-24T00:50:51.956+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8651) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-24T00:50:51.957+0000] {standard_task_runner.py:105} INFO - Job 344: Subtask dbt_test
[2025-04-24T00:50:51.958+0000] {standard_task_runner.py:72} INFO - Started process 8652 to run task
[2025-04-24T00:50:52.006+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_stock_project.dbt_test manual__2025-04-24T00:50:37.125505+00:00 [running]> on host d01273b1fd04
[2025-04-24T00:50:52.092+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_stock_project' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T00:50:37.125505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-24T00:50:37.125505+00:00'
[2025-04-24T00:50:52.093+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:50:52.111+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T00:50:52.113+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /home/***/.dbt --project-dir /opt/***/dbt']
[2025-04-24T00:50:52.121+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T00:50:54.295+0000] {subprocess.py:93} INFO - [0m00:50:54  Running with dbt=1.8.7
[2025-04-24T00:50:55.383+0000] {subprocess.py:93} INFO - [0m00:50:55  Registered adapter: snowflake=1.8.1
[2025-04-24T00:50:56.566+0000] {subprocess.py:93} INFO - [0m00:50:56  Found 6 models, 22 data tests, 3 sources, 459 macros
[2025-04-24T00:50:56.572+0000] {subprocess.py:93} INFO - [0m00:50:56
[2025-04-24T00:50:57.246+0000] {subprocess.py:93} INFO - [0m00:50:57  Concurrency: 1 threads (target='dev')
[2025-04-24T00:50:57.247+0000] {subprocess.py:93} INFO - [0m00:50:57
[2025-04-24T00:50:57.259+0000] {subprocess.py:93} INFO - [0m00:50:57  1 of 22 START test not_null_moving_averages_close_price_14d_ma ................. [RUN]
[2025-04-24T00:50:57.991+0000] {subprocess.py:93} INFO - [0m00:50:57  1 of 22 PASS not_null_moving_averages_close_price_14d_ma ....................... [[32mPASS[0m in 0.73s]
[2025-04-24T00:50:57.995+0000] {subprocess.py:93} INFO - [0m00:50:57  2 of 22 START test not_null_moving_averages_close_price_30d_ma ................. [RUN]
[2025-04-24T00:50:58.692+0000] {subprocess.py:93} INFO - [0m00:50:58  2 of 22 PASS not_null_moving_averages_close_price_30d_ma ....................... [[32mPASS[0m in 0.70s]
[2025-04-24T00:50:58.697+0000] {subprocess.py:93} INFO - [0m00:50:58  3 of 22 START test not_null_moving_averages_close_price_7d_ma .................. [RUN]
[2025-04-24T00:50:59.383+0000] {subprocess.py:93} INFO - [0m00:50:59  3 of 22 PASS not_null_moving_averages_close_price_7d_ma ........................ [[32mPASS[0m in 0.68s]
[2025-04-24T00:50:59.386+0000] {subprocess.py:93} INFO - [0m00:50:59  4 of 22 START test not_null_moving_averages_symbol ............................. [RUN]
[2025-04-24T00:51:00.335+0000] {subprocess.py:93} INFO - [0m00:51:00  4 of 22 PASS not_null_moving_averages_symbol ................................... [[32mPASS[0m in 0.95s]
[2025-04-24T00:51:00.339+0000] {subprocess.py:93} INFO - [0m00:51:00  5 of 22 START test not_null_moving_averages_trade_date ......................... [RUN]
[2025-04-24T00:51:01.061+0000] {subprocess.py:93} INFO - [0m00:51:01  5 of 22 PASS not_null_moving_averages_trade_date ............................... [[32mPASS[0m in 0.72s]
[2025-04-24T00:51:01.064+0000] {subprocess.py:93} INFO - [0m00:51:01  6 of 22 START test not_null_rsi_rsi_14d ........................................ [RUN]
[2025-04-24T00:51:01.711+0000] {subprocess.py:93} INFO - [0m00:51:01  6 of 22 PASS not_null_rsi_rsi_14d .............................................. [[32mPASS[0m in 0.64s]
[2025-04-24T00:51:01.716+0000] {subprocess.py:93} INFO - [0m00:51:01  7 of 22 START test not_null_rsi_symbol ......................................... [RUN]
[2025-04-24T00:51:02.410+0000] {subprocess.py:93} INFO - [0m00:51:02  7 of 22 PASS not_null_rsi_symbol ............................................... [[32mPASS[0m in 0.69s]
[2025-04-24T00:51:02.416+0000] {subprocess.py:93} INFO - [0m00:51:02  8 of 22 START test not_null_rsi_trade_date ..................................... [RUN]
[2025-04-24T00:51:03.049+0000] {subprocess.py:93} INFO - [0m00:51:03  8 of 22 PASS not_null_rsi_trade_date ........................................... [[32mPASS[0m in 0.63s]
[2025-04-24T00:51:03.057+0000] {subprocess.py:93} INFO - [0m00:51:03  9 of 22 START test not_null_stock_indicators_rsi_14d ........................... [RUN]
[2025-04-24T00:51:03.536+0000] {subprocess.py:93} INFO - [0m00:51:03  9 of 22 ERROR not_null_stock_indicators_rsi_14d ................................ [[31mERROR[0m in 0.48s]
[2025-04-24T00:51:03.541+0000] {subprocess.py:93} INFO - [0m00:51:03  10 of 22 START test not_null_stock_indicators_symbol ........................... [RUN]
[2025-04-24T00:51:04.146+0000] {subprocess.py:93} INFO - [0m00:51:04  10 of 22 PASS not_null_stock_indicators_symbol ................................. [[32mPASS[0m in 0.60s]
[2025-04-24T00:51:04.149+0000] {subprocess.py:93} INFO - [0m00:51:04  11 of 22 START test not_null_stock_indicators_trade_date ....................... [RUN]
[2025-04-24T00:51:04.703+0000] {subprocess.py:93} INFO - [0m00:51:04  11 of 22 PASS not_null_stock_indicators_trade_date ............................. [[32mPASS[0m in 0.55s]
[2025-04-24T00:51:04.707+0000] {subprocess.py:93} INFO - [0m00:51:04  12 of 22 START test not_null_volume_summary_symbol ............................. [RUN]
[2025-04-24T00:51:05.457+0000] {subprocess.py:93} INFO - [0m00:51:05  12 of 22 PASS not_null_volume_summary_symbol ................................... [[32mPASS[0m in 0.75s]
[2025-04-24T00:51:05.463+0000] {subprocess.py:93} INFO - [0m00:51:05  13 of 22 START test not_null_volume_summary_total_volume ....................... [RUN]
[2025-04-24T00:51:06.000+0000] {subprocess.py:93} INFO - [0m00:51:06  13 of 22 ERROR not_null_volume_summary_total_volume ............................ [[31mERROR[0m in 0.53s]
[2025-04-24T00:51:06.004+0000] {subprocess.py:93} INFO - [0m00:51:06  14 of 22 START test not_null_volume_summary_trade_date ......................... [RUN]
[2025-04-24T00:51:06.801+0000] {subprocess.py:93} INFO - [0m00:51:06  14 of 22 PASS not_null_volume_summary_trade_date ............................... [[32mPASS[0m in 0.80s]
[2025-04-24T00:51:06.807+0000] {subprocess.py:93} INFO - [0m00:51:06  15 of 22 START test positive_values_moving_averages_close_price_14d_ma ......... [RUN]
[2025-04-24T00:51:06.826+0000] {subprocess.py:93} INFO - [0m00:51:06  15 of 22 ERROR positive_values_moving_averages_close_price_14d_ma .............. [[31mERROR[0m in 0.02s]
[2025-04-24T00:51:06.833+0000] {subprocess.py:93} INFO - [0m00:51:06  16 of 22 START test positive_values_moving_averages_close_price_30d_ma ......... [RUN]
[2025-04-24T00:51:06.854+0000] {subprocess.py:93} INFO - [0m00:51:06  16 of 22 ERROR positive_values_moving_averages_close_price_30d_ma .............. [[31mERROR[0m in 0.02s]
[2025-04-24T00:51:06.859+0000] {subprocess.py:93} INFO - [0m00:51:06  17 of 22 START test positive_values_moving_averages_close_price_7d_ma .......... [RUN]
[2025-04-24T00:51:06.869+0000] {subprocess.py:93} INFO - [0m00:51:06  17 of 22 ERROR positive_values_moving_averages_close_price_7d_ma ............... [[31mERROR[0m in 0.01s]
[2025-04-24T00:51:06.873+0000] {subprocess.py:93} INFO - [0m00:51:06  18 of 22 START test range_rsi_rsi_14d__100__0 .................................. [RUN]
[2025-04-24T00:51:06.886+0000] {subprocess.py:93} INFO - [0m00:51:06  18 of 22 ERROR range_rsi_rsi_14d__100__0 ....................................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:51:06.891+0000] {subprocess.py:93} INFO - [0m00:51:06  19 of 22 START test range_stock_indicators_rsi_14d__100__0 ..................... [RUN]
[2025-04-24T00:51:06.902+0000] {subprocess.py:93} INFO - [0m00:51:06  19 of 22 ERROR range_stock_indicators_rsi_14d__100__0 .......................... [[31mERROR[0m in 0.01s]
[2025-04-24T00:51:06.906+0000] {subprocess.py:93} INFO - [0m00:51:06  20 of 22 START test relationships_moving_averages_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-24T00:51:07.720+0000] {subprocess.py:93} INFO - [0m00:51:07  20 of 22 PASS relationships_moving_averages_symbol__symbol__source_raw_stock_ .. [[32mPASS[0m in 0.81s]
[2025-04-24T00:51:07.724+0000] {subprocess.py:93} INFO - [0m00:51:07  21 of 22 START test relationships_rsi_symbol__symbol__source_raw_stock_ ........ [RUN]
[2025-04-24T00:51:08.501+0000] {subprocess.py:93} INFO - [0m00:51:08  21 of 22 PASS relationships_rsi_symbol__symbol__source_raw_stock_ .............. [[32mPASS[0m in 0.78s]
[2025-04-24T00:51:08.506+0000] {subprocess.py:93} INFO - [0m00:51:08  22 of 22 START test relationships_stock_indicators_symbol__symbol__source_raw_stock_  [RUN]
[2025-04-24T00:51:09.237+0000] {subprocess.py:93} INFO - [0m00:51:09  22 of 22 PASS relationships_stock_indicators_symbol__symbol__source_raw_stock_ . [[32mPASS[0m in 0.73s]
[2025-04-24T00:51:09.243+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.244+0000] {subprocess.py:93} INFO - [0m00:51:09  Finished running 22 data tests in 0 hours 0 minutes and 12.67 seconds (12.67s).
[2025-04-24T00:51:09.357+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.358+0000] {subprocess.py:93} INFO - [0m00:51:09  [31mCompleted with 7 errors and 0 warnings:[0m
[2025-04-24T00:51:09.359+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.360+0000] {subprocess.py:93} INFO - [0m00:51:09    Database Error in test not_null_stock_indicators_rsi_14d (models/output/schema.yml)
[2025-04-24T00:51:09.360+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-24T00:51:09.361+0000] {subprocess.py:93} INFO -   invalid identifier 'RSI_14D'
[2025-04-24T00:51:09.361+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_stock_indicators_rsi_14d.sql
[2025-04-24T00:51:09.362+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.362+0000] {subprocess.py:93} INFO - [0m00:51:09    Database Error in test not_null_volume_summary_total_volume (models/output/schema.yml)
[2025-04-24T00:51:09.363+0000] {subprocess.py:93} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2025-04-24T00:51:09.364+0000] {subprocess.py:93} INFO -   invalid identifier 'TOTAL_VOLUME'
[2025-04-24T00:51:09.365+0000] {subprocess.py:93} INFO -   compiled code at target/run/dbt_stock_project/models/output/schema.yml/not_null_volume_summary_total_volume.sql
[2025-04-24T00:51:09.366+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.368+0000] {subprocess.py:93} INFO - [0m00:51:09    Compilation Error in test positive_values_moving_averages_close_price_14d_ma (models/output/schema.yml)
[2025-04-24T00:51:09.369+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:51:09.370+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.371+0000] {subprocess.py:93} INFO - [0m00:51:09    Compilation Error in test positive_values_moving_averages_close_price_30d_ma (models/output/schema.yml)
[2025-04-24T00:51:09.372+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:51:09.373+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.374+0000] {subprocess.py:93} INFO - [0m00:51:09    Compilation Error in test positive_values_moving_averages_close_price_7d_ma (models/output/schema.yml)
[2025-04-24T00:51:09.375+0000] {subprocess.py:93} INFO -   'test_positive_values' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:51:09.375+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.376+0000] {subprocess.py:93} INFO - [0m00:51:09    Compilation Error in test range_rsi_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T00:51:09.376+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:51:09.377+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.378+0000] {subprocess.py:93} INFO - [0m00:51:09    Compilation Error in test range_stock_indicators_rsi_14d__100__0 (models/output/schema.yml)
[2025-04-24T00:51:09.378+0000] {subprocess.py:93} INFO -   'test_range' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-04-24T00:51:09.379+0000] {subprocess.py:93} INFO - [0m00:51:09
[2025-04-24T00:51:09.380+0000] {subprocess.py:93} INFO - [0m00:51:09  Done. PASS=15 WARN=0 ERROR=7 SKIP=0 TOTAL=22
[2025-04-24T00:51:10.280+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T00:51:10.293+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:51:10.297+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_stock_project, task_id=dbt_test, run_id=manual__2025-04-24T00:50:37.125505+00:00, execution_date=20250424T005037, start_date=20250424T005051, end_date=20250424T005110
[2025-04-24T00:51:10.314+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T00:51:10.315+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 344 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 8652)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T00:51:10.333+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-24T00:51:10.365+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T00:51:10.373+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
